import { notFound } from 'next/navigation';
import Link from 'next/link';
import { SUNGRID_CASE_STUDY } from '@/showcase/content/case-studies/sungrid-energy';
import { NORTHSTAR_CASE_STUDY } from '@/showcase/content/case-studies/northstar-clinic';
import { EMBER_CASE_STUDY } from '@/showcase/content/case-studies/ember-table';
import { HAVEN_CASE_STUDY } from '@/showcase/content/case-studies/haven-realty';
import { MERIDIAN_CASE_STUDY } from '@/showcase/content/case-studies/meridian-legal';
import { FORGE_CASE_STUDY } from '@/showcase/content/case-studies/forge-build';
import { CRESTFIELD_CASE_STUDY } from '@/showcase/content/case-studies/crestfield-academy';
import { ATELIER_CASE_STUDY } from '@/showcase/content/case-studies/atelier-soso';
const studies = { 'sungrid-energy': SUNGRID_CASE_STUDY, 'northstar-clinic': NORTHSTAR_CASE_STUDY, 'ember-table': EMBER_CASE_STUDY, 'haven-realty': HAVEN_CASE_STUDY, 'meridian-legal': MERIDIAN_CASE_STUDY, 'forge-build': FORGE_CASE_STUDY, 'crestfield-academy': CRESTFIELD_CASE_STUDY, 'atelier-soso': ATELIER_CASE_STUDY };
export default async function CaseStudyPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const study = studies[slug as keyof typeof studies]; if (!study) notFound(); return <main className="mx-auto max-w-3xl px-6 py-20"><p className="text-sm font-semibold uppercase tracking-[.18em] text-slate-500">{study.projectType}</p><h1 className="mt-4 text-5xl font-semibold tracking-tight">{study.name}</h1><p className="mt-6 text-xl text-slate-600">{study.executiveSummary}</p><div className="mt-10 space-y-8">{[['Problem', study.problem], ['Strategy', study.strategy], ['Solution', study.solution], ['Delivery', study.delivery], ['Quality', study.quality], ['Delivered', study.deliveredResult]].map(([title, copy]) => <section key={title}><h2 className="text-xl font-semibold">{title}</h2><p className="mt-2 text-slate-700">{copy}</p></section>)}</div><section className="mt-10 rounded-xl bg-slate-50 p-6"><h2 className="font-semibold">Designed impact</h2><ul className="mt-3 list-disc space-y-2 pl-5">{study.outcomes.designedImpact.map((item) => <li key={item}>{item}</li>)}</ul><h2 className="mt-6 font-semibold">Limitations</h2><ul className="mt-3 list-disc space-y-2 pl-5">{study.outcomes.limitations.map((item) => <li key={item}>{item}</li>)}</ul></section><p className="mt-10 text-sm text-slate-500">{study.disclosure}</p>{study.demoUrl ? <Link className="mt-6 inline-block underline" href={study.demoUrl}>View demonstrator →</Link> : null}</main>; }
