-- Booka staging core forward migrations
-- Generated by scripts/generate-staging-sql-editor-release.mjs.
-- Run only against the intended staging Supabase database after backup/preflight.

-- BEGIN db/migrations/122_business_events.sql
-- 122_business_events.sql — append-only merchant activity timeline
CREATE TABLE IF NOT EXISTS public.business_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  actor_type text NOT NULL CHECK (actor_type IN ('user', 'staff', 'customer', 'ai', 'system')),
  actor_id uuid,
  action text NOT NULL,
  entity_type text,
  entity_id uuid,
  source text NOT NULL DEFAULT 'system' CHECK (source IN ('whatsapp', 'dashboard', 'api', 'system')),
  before jsonb,
  after jsonb,
  reason text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_business_events_tenant_created
  ON public.business_events (tenant_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_business_events_entity
  ON public.business_events (tenant_id, entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_business_events_action
  ON public.business_events (tenant_id, action, created_at DESC);

ALTER TABLE public.business_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS business_events_service_role ON public.business_events;
CREATE POLICY business_events_service_role ON public.business_events
  AS PERMISSIVE FOR ALL TO service_role USING (true) WITH CHECK (true);
-- END db/migrations/122_business_events.sql

-- BEGIN db/migrations/123_reconciliation.sql
-- 123_reconciliation.sql — daily close runs + review items
CREATE TABLE IF NOT EXISTS public.reconciliation_runs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  business_date date NOT NULL,
  timezone text NOT NULL,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'computed', 'delivered', 'failed')),
  currency text NOT NULL DEFAULT 'NGN',
  expected_revenue_cents bigint NOT NULL DEFAULT 0,
  adjusted_expected_cents bigint NOT NULL DEFAULT 0,
  recorded_payments_cents bigint NOT NULL DEFAULT 0,
  approved_outstanding_cents bigint NOT NULL DEFAULT 0,
  revenue_gap_cents bigint NOT NULL DEFAULT 0,
  breakdown jsonb NOT NULL DEFAULT '{}'::jsonb,
  computed_at timestamptz,
  delivered_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT reconciliation_runs_unique_day UNIQUE (tenant_id, business_date)
);

CREATE TABLE IF NOT EXISTS public.reconciliation_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  run_id uuid NOT NULL REFERENCES public.reconciliation_runs(id) ON DELETE CASCADE,
  item_type text NOT NULL CHECK (item_type IN ('unpaid_completed_service', 'delivered_unpaid_order', 'discount_without_reason')),
  severity text NOT NULL DEFAULT 'medium' CHECK (severity IN ('low', 'medium', 'high')),
  entity_type text,
  entity_id uuid,
  expected_cents bigint,
  actual_cents bigint,
  difference_cents bigint,
  detail jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_reconciliation_items_run
  ON public.reconciliation_items (run_id);

ALTER TABLE public.reconciliation_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reconciliation_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS reconciliation_runs_service_role ON public.reconciliation_runs;
CREATE POLICY reconciliation_runs_service_role ON public.reconciliation_runs
  AS PERMISSIVE FOR ALL TO service_role USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS reconciliation_items_service_role ON public.reconciliation_items;
CREATE POLICY reconciliation_items_service_role ON public.reconciliation_items
  AS PERMISSIVE FOR ALL TO service_role USING (true) WITH CHECK (true);
-- END db/migrations/123_reconciliation.sql

-- BEGIN db/migrations/124_ledger_columns.sql
-- 124_ledger_columns.sql — additive merchant reconciliation fields + tenant close settings
ALTER TABLE public.transactions
  ADD COLUMN IF NOT EXISTS subject_type text CHECK (subject_type IN ('reservation', 'retail_order')),
  ADD COLUMN IF NOT EXISTS subject_id uuid;

CREATE INDEX IF NOT EXISTS idx_transactions_subject
  ON public.transactions (tenant_id, subject_type, subject_id);

ALTER TABLE public.reservations
  ADD COLUMN IF NOT EXISTS price_cents_snapshot bigint,
  ADD COLUMN IF NOT EXISTS discount_cents bigint NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS discount_reason text,
  ADD COLUMN IF NOT EXISTS completed_at timestamptz;

ALTER TABLE public.retail_orders
  ADD COLUMN IF NOT EXISTS discount_cents bigint NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS delivery_fee_cents bigint NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS amount_paid_cents bigint NOT NULL DEFAULT 0;

ALTER TABLE public.tenants
  ADD COLUMN IF NOT EXISTS close_report_enabled boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS close_report_time time NOT NULL DEFAULT '20:00';
-- END db/migrations/124_ledger_columns.sql

-- BEGIN db/migrations/125_ai_action_log.sql
CREATE TABLE IF NOT EXISTS public.ai_action_log (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id         uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  actor_type        text NOT NULL,
  actor_id          uuid,
  channel           text,
  raw_message       text,
  action            text NOT NULL,
  params            jsonb NOT NULL DEFAULT '{}'::jsonb,
  idempotency_key   text NOT NULL,
  validation_result jsonb,
  outcome           text NOT NULL CHECK (outcome IN ('executed','rejected','needs_confirmation','duplicate','denied')),
  model             text,
  created_at        timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT ai_action_log_idem_unique UNIQUE (tenant_id, idempotency_key)
);

ALTER TABLE public.ai_action_log ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS ai_action_log_service_role ON public.ai_action_log;
CREATE POLICY ai_action_log_service_role
  ON public.ai_action_log
  AS PERMISSIVE
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- END db/migrations/125_ai_action_log.sql

-- BEGIN db/migrations/126_inventory_movements_commerce.sql
ALTER TABLE public.inventory_movements
  ADD COLUMN IF NOT EXISTS unit_cost_cents integer;

ALTER TABLE public.inventory_movements
  DROP CONSTRAINT IF EXISTS inventory_movements_movement_type_check;

ALTER TABLE public.inventory_movements
  ADD CONSTRAINT inventory_movements_movement_type_check
  CHECK (
    movement_type IN (
      'sale',
      'damage',
      'adjustment',
      'purchase',
      'return',
      'refund_restock',
      'transfer_in',
      'transfer_out',
      'count_adjustment',
      'service_consumption',
      'expiry',
      'manual_adjustment'
    )
  );

ALTER TABLE public.customers
  ADD COLUMN IF NOT EXISTS tags text[] NOT NULL DEFAULT '{}'::text[];

CREATE OR REPLACE FUNCTION public.update_inventory(
  p_tenant_id uuid,
  p_product_id uuid,
  p_variant_id uuid,
  p_quantity_change integer,
  p_movement_type text,
  p_reference_type text,
  p_reference_id text,
  p_reason text,
  p_performed_by uuid,
  p_unit_cost_cents integer DEFAULT NULL
)
RETURNS TABLE (movement_id uuid, previous_quantity integer, new_quantity integer)
LANGUAGE plpgsql
AS $function$
DECLARE
  v_prev integer;
  v_new integer;
  v_movement_id uuid;
BEGIN
  IF p_variant_id IS NOT NULL THEN
    SELECT COALESCE(stock_quantity, 0) INTO v_prev
    FROM product_variants
    WHERE id = p_variant_id
    FOR UPDATE;

    IF v_prev IS NULL THEN
      RAISE EXCEPTION 'Variant % not found', p_variant_id;
    END IF;

    v_new := GREATEST(0, v_prev + p_quantity_change);

    UPDATE product_variants
      SET stock_quantity = v_new,
          updated_at = now()
    WHERE id = p_variant_id;
  ELSE
    SELECT COALESCE(stock_quantity, 0) INTO v_prev
    FROM products
    WHERE id = p_product_id
      AND tenant_id = p_tenant_id
    FOR UPDATE;

    IF v_prev IS NULL THEN
      RAISE EXCEPTION 'Product % not found for tenant %', p_product_id, p_tenant_id;
    END IF;

    v_new := GREATEST(0, v_prev + p_quantity_change);

    UPDATE products
      SET stock_quantity = v_new,
          updated_at = now()
    WHERE id = p_product_id
      AND tenant_id = p_tenant_id;
  END IF;

  INSERT INTO inventory_movements (
    tenant_id,
    product_id,
    variant_id,
    movement_type,
    quantity,
    quantity_change,
    previous_quantity,
    new_quantity,
    reference_type,
    reference_id,
    reason,
    performed_by,
    created_by,
    unit_cost_cents
  ) VALUES (
    p_tenant_id,
    p_product_id,
    p_variant_id,
    p_movement_type,
    ABS(p_quantity_change),
    p_quantity_change,
    v_prev,
    v_new,
    p_reference_type,
    p_reference_id,
    p_reason,
    p_performed_by,
    p_performed_by,
    p_unit_cost_cents
  )
  RETURNING id INTO v_movement_id;

  movement_id := v_movement_id;
  previous_quantity := v_prev;
  new_quantity := v_new;
  RETURN NEXT;
END;
$function$;
-- END db/migrations/126_inventory_movements_commerce.sql

-- BEGIN db/migrations/127_record_retail_sale_fn.sql
BEGIN;

CREATE OR REPLACE FUNCTION public.record_retail_sale_tx(
  p_tenant_id uuid,
  p_actor_user_id uuid,
  p_items jsonb,
  p_customer_id uuid DEFAULT NULL,
  p_external_customer_ref text DEFAULT NULL,
  p_source_chat_id uuid DEFAULT NULL,
  p_currency text DEFAULT 'NGN',
  p_notes text DEFAULT NULL,
  p_reference_key text DEFAULT NULL,
  p_metadata jsonb DEFAULT '{}'::jsonb
)
RETURNS TABLE (
  order_id uuid,
  transaction_id uuid,
  total_cents integer,
  item_count integer
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_order_id uuid;
  v_transaction_id uuid;
  v_total_cents integer := 0;
  v_item_count integer := 0;
  v_reference_key text := COALESCE(NULLIF(trim(p_reference_key), ''), concat('retail_pos_', replace(gen_random_uuid()::text, '-', '')));
  v_item record;
  v_track_inventory boolean;
  v_quantity integer;
  v_unit_price integer;
  v_line_total integer;
BEGIN
  IF p_items IS NULL OR jsonb_typeof(p_items) <> 'array' OR jsonb_array_length(p_items) = 0 THEN
    RAISE EXCEPTION 'record_retail_sale_tx requires at least one item';
  END IF;

  INSERT INTO public.retail_orders (
    tenant_id,
    customer_id,
    source_chat_id,
    external_customer_ref,
    status,
    payment_status,
    fulfillment_status,
    currency,
    subtotal_cents,
    total_cents,
    notes,
    metadata
  )
  VALUES (
    p_tenant_id,
    p_customer_id,
    p_source_chat_id,
    p_external_customer_ref,
    'fulfilled',
    'paid',
    'fulfilled',
    COALESCE(NULLIF(trim(p_currency), ''), 'NGN'),
    0,
    0,
    p_notes,
    COALESCE(p_metadata, '{}'::jsonb) || jsonb_build_object(
      'source', 'pos',
      'paidAt', now(),
      'paidBy', p_actor_user_id,
      'fulfilledAt', now(),
      'fulfilledBy', p_actor_user_id,
      'inventoryAppliedAt', now(),
      'inventoryAppliedBy', p_actor_user_id,
      'retailSaleAttributedAt', now()
    )
  )
  RETURNING id INTO v_order_id;

  FOR v_item IN
    SELECT *
    FROM jsonb_to_recordset(p_items) AS x(
      product_id uuid,
      variant_id uuid,
      quantity integer,
      unit_price_cents integer,
      total_price_cents integer,
      metadata jsonb
    )
  LOOP
    v_quantity := GREATEST(COALESCE(v_item.quantity, 0), 0);
    v_unit_price := GREATEST(COALESCE(v_item.unit_price_cents, 0), 0);
    v_line_total := COALESCE(v_item.total_price_cents, v_unit_price * v_quantity);

    IF v_item.product_id IS NULL OR v_quantity <= 0 THEN
      RAISE EXCEPTION 'retail sale items require product_id and positive quantity';
    END IF;

    INSERT INTO public.retail_order_items (
      order_id,
      tenant_id,
      product_id,
      variant_id,
      quantity,
      unit_price_cents,
      total_price_cents,
      metadata
    )
    VALUES (
      v_order_id,
      p_tenant_id,
      v_item.product_id,
      v_item.variant_id,
      v_quantity,
      v_unit_price,
      v_line_total,
      COALESCE(v_item.metadata, '{}'::jsonb)
    );

    SELECT COALESCE(track_inventory, false)
    INTO v_track_inventory
    FROM public.products
    WHERE id = v_item.product_id
      AND tenant_id = p_tenant_id;

    IF COALESCE(v_track_inventory, false) THEN
      PERFORM public.update_inventory(
        p_tenant_id,
        v_item.product_id,
        v_item.variant_id,
        -v_quantity,
        'sale',
        'retail_order',
        v_order_id::text,
        format('Retail POS sale %s', v_order_id),
        p_actor_user_id,
        NULL
      );
    END IF;

    v_total_cents := v_total_cents + v_line_total;
    v_item_count := v_item_count + v_quantity;
  END LOOP;

  UPDATE public.retail_orders
  SET subtotal_cents = v_total_cents,
      total_cents = v_total_cents,
      updated_at = now()
  WHERE id = v_order_id;

  INSERT INTO public.transactions (
    tenant_id,
    amount,
    currency,
    type,
    status,
    subject_type,
    subject_id,
    provider_reference,
    raw
  )
  VALUES (
    p_tenant_id,
    v_total_cents / 100.0,
    COALESCE(NULLIF(trim(p_currency), ''), 'NGN'),
    'sale',
    'success',
    'retail_order',
    v_order_id,
    v_reference_key,
    jsonb_build_object(
      'source', 'pos',
      'provider', 'internal',
      'retail_order_id', v_order_id,
      'item_count', v_item_count,
      'actor_user_id', p_actor_user_id
    )
  )
  RETURNING id INTO v_transaction_id;

  RETURN QUERY
  SELECT v_order_id, v_transaction_id, v_total_cents, v_item_count;
END;
$$;

CREATE OR REPLACE FUNCTION public.refund_retail_sale_tx(
  p_tenant_id uuid,
  p_order_id uuid,
  p_actor_user_id uuid,
  p_reason text DEFAULT NULL,
  p_reference_key text DEFAULT NULL
)
RETURNS TABLE (
  order_id uuid,
  refund_transaction_id uuid,
  total_cents integer
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_order record;
  v_sale_transaction_id uuid;
  v_existing_refund_id uuid;
  v_refund_transaction_id uuid;
  v_reference_key text := COALESCE(NULLIF(trim(p_reference_key), ''), concat('retail_refund_', replace(gen_random_uuid()::text, '-', '')));
  v_item record;
  v_track_inventory boolean;
BEGIN
  SELECT *
  INTO v_order
  FROM public.retail_orders
  WHERE id = p_order_id
    AND tenant_id = p_tenant_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Retail order not found';
  END IF;

  IF v_order.payment_status = 'refunded' THEN
    SELECT id
    INTO v_existing_refund_id
    FROM public.transactions
    WHERE tenant_id = p_tenant_id
      AND subject_type = 'retail_order'
      AND subject_id = p_order_id
      AND type = 'refund'
    ORDER BY created_at DESC
    LIMIT 1;

    RETURN QUERY
    SELECT p_order_id, v_existing_refund_id, COALESCE(v_order.total_cents, 0);
    RETURN;
  END IF;

  SELECT id
  INTO v_sale_transaction_id
  FROM public.transactions
  WHERE tenant_id = p_tenant_id
    AND subject_type = 'retail_order'
    AND subject_id = p_order_id
    AND type = 'sale'
  ORDER BY created_at DESC
  LIMIT 1;

  FOR v_item IN
    SELECT roi.product_id, roi.variant_id, roi.quantity
    FROM public.retail_order_items roi
    WHERE roi.order_id = p_order_id
  LOOP
    SELECT COALESCE(track_inventory, false)
    INTO v_track_inventory
    FROM public.products
    WHERE id = v_item.product_id
      AND tenant_id = p_tenant_id;

    IF COALESCE(v_track_inventory, false) THEN
      PERFORM public.update_inventory(
        p_tenant_id,
        v_item.product_id,
        v_item.variant_id,
        GREATEST(COALESCE(v_item.quantity, 0), 0),
        'refund_restock',
        'retail_order',
        p_order_id::text,
        COALESCE(p_reason, format('Retail POS refund %s', p_order_id)),
        p_actor_user_id,
        NULL
      );
    END IF;
  END LOOP;

  UPDATE public.retail_orders
  SET status = 'cancelled',
      payment_status = 'refunded',
      fulfillment_status = 'cancelled',
      metadata = COALESCE(metadata, '{}'::jsonb) || jsonb_build_object(
        'refundedAt', now(),
        'refundedBy', p_actor_user_id,
        'inventoryRevertedAt', now()
      ),
      updated_at = now()
  WHERE id = p_order_id
    AND tenant_id = p_tenant_id;

  INSERT INTO public.transactions (
    tenant_id,
    original_transaction_id,
    amount,
    currency,
    type,
    status,
    subject_type,
    subject_id,
    provider_reference,
    refund_amount,
    refund_reason,
    raw
  )
  VALUES (
    p_tenant_id,
    v_sale_transaction_id,
    -(COALESCE(v_order.total_cents, 0) / 100.0),
    COALESCE(v_order.currency, 'NGN'),
    'refund',
    'completed',
    'retail_order',
    p_order_id,
    v_reference_key,
    COALESCE(v_order.total_cents, 0) / 100.0,
    p_reason,
    jsonb_build_object(
      'source', 'pos',
      'provider', 'internal',
      'retail_order_id', p_order_id,
      'original_transaction_id', v_sale_transaction_id,
      'actor_user_id', p_actor_user_id
    )
  )
  RETURNING id INTO v_refund_transaction_id;

  RETURN QUERY
  SELECT p_order_id, v_refund_transaction_id, COALESCE(v_order.total_cents, 0);
END;
$$;

GRANT EXECUTE ON FUNCTION public.record_retail_sale_tx(uuid, uuid, jsonb, uuid, text, uuid, text, text, text, jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.refund_retail_sale_tx(uuid, uuid, uuid, text, text) TO service_role;

COMMIT;
-- END db/migrations/127_record_retail_sale_fn.sql

-- BEGIN db/migrations/128_business_anomalies.sql
BEGIN;

CREATE TABLE IF NOT EXISTS public.business_anomalies (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  rule_key text NOT NULL,
  domain text NOT NULL CHECK (domain IN ('service', 'retail', 'inventory')),
  severity text NOT NULL CHECK (severity IN ('low', 'medium', 'high', 'critical')),
  status text NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'investigating', 'resolved', 'dismissed', 'false_positive')),
  entity_type text,
  entity_id uuid,
  expected_value_cents bigint,
  actual_value_cents bigint,
  difference_cents bigint,
  detection_source text NOT NULL CHECK (detection_source IN ('reconciliation', 'realtime_event')),
  first_detected_at timestamptz NOT NULL DEFAULT now(),
  last_seen_at timestamptz NOT NULL DEFAULT now(),
  dedup_key text NOT NULL,
  assigned_to uuid,
  assigned_at timestamptz,
  resolution_note text,
  resolved_by uuid,
  resolved_at timestamptz,
  run_id uuid REFERENCES public.reconciliation_runs(id) ON DELETE SET NULL,
  detail jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_business_anomalies_open
  ON public.business_anomalies (tenant_id, dedup_key)
  WHERE status IN ('open', 'investigating');

CREATE INDEX IF NOT EXISTS idx_business_anomalies_status
  ON public.business_anomalies (tenant_id, status, severity);

ALTER TABLE public.reconciliation_items
  ADD COLUMN IF NOT EXISTS anomaly_id uuid REFERENCES public.business_anomalies(id) ON DELETE SET NULL;

ALTER TABLE public.business_anomalies ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS business_anomalies_service_role ON public.business_anomalies;
CREATE POLICY business_anomalies_service_role ON public.business_anomalies
  AS PERMISSIVE FOR ALL TO service_role
  USING (true)
  WITH CHECK (true);

COMMIT;
-- END db/migrations/128_business_anomalies.sql

-- BEGIN db/migrations/129_tenant_user_permissions.sql
CREATE TABLE IF NOT EXISTS public.tenant_user_permissions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  tenant_user_id uuid NOT NULL REFERENCES public.tenant_users(id) ON DELETE CASCADE,
  permission text NOT NULL,
  effect text NOT NULL CHECK (effect IN ('grant', 'revoke')),
  reason text,
  created_by uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT tenant_user_permissions_unique UNIQUE (tenant_id, tenant_user_id, permission)
);

ALTER TABLE public.tenant_user_permissions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_user_permissions_service_role ON public.tenant_user_permissions;
CREATE POLICY tenant_user_permissions_service_role
  ON public.tenant_user_permissions
  AS PERMISSIVE
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- END db/migrations/129_tenant_user_permissions.sql

-- BEGIN db/migrations/130_inventory_locations_counts.sql
CREATE TABLE IF NOT EXISTS public.inventory_locations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  name text NOT NULL,
  is_default boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.inventory_movements
  ADD COLUMN IF NOT EXISTS location_id uuid REFERENCES public.inventory_locations(id) ON DELETE SET NULL;

CREATE OR REPLACE FUNCTION public.update_inventory(
  p_tenant_id uuid,
  p_product_id uuid,
  p_variant_id uuid,
  p_quantity_change integer,
  p_movement_type text,
  p_reference_type text,
  p_reference_id text,
  p_reason text,
  p_performed_by uuid,
  p_unit_cost_cents integer DEFAULT NULL,
  p_location_id uuid DEFAULT NULL
)
RETURNS TABLE (movement_id uuid, previous_quantity integer, new_quantity integer)
LANGUAGE plpgsql
AS $function$
DECLARE
  v_prev integer;
  v_new integer;
  v_movement_id uuid;
BEGIN
  IF p_variant_id IS NOT NULL THEN
    SELECT COALESCE(stock_quantity, 0) INTO v_prev
    FROM product_variants
    WHERE id = p_variant_id
    FOR UPDATE;

    IF v_prev IS NULL THEN
      RAISE EXCEPTION 'Variant % not found', p_variant_id;
    END IF;

    v_new := GREATEST(0, v_prev + p_quantity_change);

    UPDATE product_variants
      SET stock_quantity = v_new,
          updated_at = now()
    WHERE id = p_variant_id;
  ELSE
    SELECT COALESCE(stock_quantity, 0) INTO v_prev
    FROM products
    WHERE id = p_product_id
      AND tenant_id = p_tenant_id
    FOR UPDATE;

    IF v_prev IS NULL THEN
      RAISE EXCEPTION 'Product % not found for tenant %', p_product_id, p_tenant_id;
    END IF;

    v_new := GREATEST(0, v_prev + p_quantity_change);

    UPDATE products
      SET stock_quantity = v_new,
          updated_at = now()
    WHERE id = p_product_id
      AND tenant_id = p_tenant_id;
  END IF;

  INSERT INTO inventory_movements (
    tenant_id,
    product_id,
    variant_id,
    movement_type,
    quantity,
    quantity_change,
    previous_quantity,
    new_quantity,
    reference_type,
    reference_id,
    reason,
    performed_by,
    created_by,
    unit_cost_cents,
    location_id
  ) VALUES (
    p_tenant_id,
    p_product_id,
    p_variant_id,
    p_movement_type,
    ABS(p_quantity_change),
    p_quantity_change,
    v_prev,
    v_new,
    p_reference_type,
    p_reference_id,
    p_reason,
    p_performed_by,
    p_performed_by,
    p_unit_cost_cents,
    p_location_id
  )
  RETURNING id INTO v_movement_id;

  movement_id := v_movement_id;
  previous_quantity := v_prev;
  new_quantity := v_new;
  RETURN NEXT;
END;
$function$;

CREATE TABLE IF NOT EXISTS public.stock_count_sessions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  location_id uuid REFERENCES public.inventory_locations(id) ON DELETE SET NULL,
  status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','counting','review','approved','cancelled')),
  started_by uuid,
  snapshot_at timestamptz,
  approved_by uuid,
  approved_at timestamptz,
  shrinkage_value_cents bigint NOT NULL DEFAULT 0,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_active_session
  ON public.stock_count_sessions (tenant_id, location_id)
  WHERE status IN ('draft', 'counting', 'review');

CREATE TABLE IF NOT EXISTS public.stock_count_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  session_id uuid NOT NULL REFERENCES public.stock_count_sessions(id) ON DELETE CASCADE,
  product_id uuid NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  variant_id uuid REFERENCES public.product_variants(id) ON DELETE SET NULL,
  location_id uuid REFERENCES public.inventory_locations(id) ON DELETE SET NULL,
  expected_quantity integer NOT NULL,
  counted_quantity integer,
  variance integer,
  unit_cost_cents integer,
  variance_value_cents bigint,
  flags jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.inventory_locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_count_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_count_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS inventory_locations_service_role ON public.inventory_locations;
CREATE POLICY inventory_locations_service_role
  ON public.inventory_locations
  AS PERMISSIVE
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

DROP POLICY IF EXISTS stock_count_sessions_service_role ON public.stock_count_sessions;
CREATE POLICY stock_count_sessions_service_role
  ON public.stock_count_sessions
  AS PERMISSIVE
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

DROP POLICY IF EXISTS stock_count_items_service_role ON public.stock_count_items;
CREATE POLICY stock_count_items_service_role
  ON public.stock_count_items
  AS PERMISSIVE
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

INSERT INTO public.inventory_locations (tenant_id, name, is_default)
SELECT t.id, 'Main', true
FROM public.tenants t
WHERE NOT EXISTS (
  SELECT 1
  FROM public.inventory_locations l
  WHERE l.tenant_id = t.id
    AND l.is_default = true
);
-- END db/migrations/130_inventory_locations_counts.sql

-- BEGIN db/migrations/131_approvals.sql
CREATE TABLE IF NOT EXISTS public.tenant_approval_policies (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  request_type text NOT NULL CHECK (request_type IN ('discount', 'refund', 'stock_adjustment')),
  role text NOT NULL,
  max_self_approve numeric NOT NULL,
  requires_permission text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT tenant_approval_policies_unique UNIQUE (tenant_id, request_type, role)
);

CREATE TABLE IF NOT EXISTS public.approval_requests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  request_type text NOT NULL CHECK (request_type IN ('discount', 'refund', 'stock_adjustment')),
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected', 'expired')),
  requested_by uuid,
  subject_type text,
  subject_id uuid,
  amount numeric,
  percent numeric,
  reason text,
  action_payload jsonb NOT NULL,
  required_permission text NOT NULL,
  expires_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.approval_actions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  request_id uuid NOT NULL REFERENCES public.approval_requests(id) ON DELETE CASCADE,
  actor_id uuid,
  decision text NOT NULL CHECK (decision IN ('approve', 'reject')),
  note text,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.tenant_approval_policies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.approval_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.approval_actions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_approval_policies_service_role ON public.tenant_approval_policies;
CREATE POLICY tenant_approval_policies_service_role
  ON public.tenant_approval_policies
  AS PERMISSIVE
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

DROP POLICY IF EXISTS approval_requests_service_role ON public.approval_requests;
CREATE POLICY approval_requests_service_role
  ON public.approval_requests
  AS PERMISSIVE
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

DROP POLICY IF EXISTS approval_actions_service_role ON public.approval_actions;
CREATE POLICY approval_actions_service_role
  ON public.approval_actions
  AS PERMISSIVE
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- END db/migrations/131_approvals.sql

-- BEGIN db/migrations/132_recipes_uom.sql
ALTER TABLE public.products
  ADD COLUMN IF NOT EXISTS base_uom text
    CHECK (base_uom IS NULL OR base_uom IN ('piece', 'pack', 'ml', 'l', 'g', 'kg')),
  ADD COLUMN IF NOT EXISTS pack_size numeric
    CHECK (pack_size IS NULL OR pack_size > 0);

CREATE TABLE IF NOT EXISTS public.service_material_recipes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  service_id uuid NOT NULL REFERENCES public.services(id) ON DELETE CASCADE,
  is_active boolean NOT NULL DEFAULT true,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT service_material_recipes_unique_service UNIQUE (tenant_id, service_id)
);

CREATE INDEX IF NOT EXISTS idx_service_material_recipes_tenant_service
  ON public.service_material_recipes (tenant_id, service_id);

CREATE TABLE IF NOT EXISTS public.service_material_recipe_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  recipe_id uuid NOT NULL REFERENCES public.service_material_recipes(id) ON DELETE CASCADE,
  product_id uuid NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  variant_id uuid REFERENCES public.product_variants(id) ON DELETE SET NULL,
  default_quantity numeric NOT NULL CHECK (default_quantity > 0),
  uom text NOT NULL CHECK (uom IN ('piece', 'pack', 'ml', 'l', 'g', 'kg')),
  is_optional boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_service_material_recipe_items_recipe
  ON public.service_material_recipe_items (recipe_id);

CREATE INDEX IF NOT EXISTS idx_service_material_recipe_items_product
  ON public.service_material_recipe_items (tenant_id, product_id);

CREATE TABLE IF NOT EXISTS public.service_consumption_records (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  reservation_id uuid NOT NULL REFERENCES public.reservations(id) ON DELETE CASCADE,
  service_id uuid NOT NULL REFERENCES public.services(id) ON DELETE CASCADE,
  product_id uuid NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  variant_id uuid REFERENCES public.product_variants(id) ON DELETE SET NULL,
  planned_quantity numeric NOT NULL CHECK (planned_quantity > 0),
  actual_quantity numeric,
  uom text NOT NULL CHECK (uom IN ('piece', 'pack', 'ml', 'l', 'g', 'kg')),
  staff_id uuid REFERENCES public.tenant_users(id) ON DELETE SET NULL,
  movement_id uuid REFERENCES public.inventory_movements(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_service_consumption_records_reservation
  ON public.service_consumption_records (tenant_id, reservation_id);

CREATE INDEX IF NOT EXISTS idx_service_consumption_records_service
  ON public.service_consumption_records (tenant_id, service_id, created_at DESC);

ALTER TABLE public.service_material_recipes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.service_material_recipe_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.service_consumption_records ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS service_material_recipes_service_role ON public.service_material_recipes;
CREATE POLICY service_material_recipes_service_role
  ON public.service_material_recipes
  AS PERMISSIVE
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

DROP POLICY IF EXISTS service_material_recipe_items_service_role ON public.service_material_recipe_items;
CREATE POLICY service_material_recipe_items_service_role
  ON public.service_material_recipe_items
  AS PERMISSIVE
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

DROP POLICY IF EXISTS service_consumption_records_service_role ON public.service_consumption_records;
CREATE POLICY service_consumption_records_service_role
  ON public.service_consumption_records
  AS PERMISSIVE
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- END db/migrations/132_recipes_uom.sql

-- BEGIN db/migrations/133_customer_memory.sql
BEGIN;

CREATE OR REPLACE FUNCTION public.normalize_customer_phone(raw text)
RETURNS text
LANGUAGE plpgsql
IMMUTABLE
AS $$
DECLARE
  digits text;
BEGIN
  IF raw IS NULL OR btrim(raw) = '' THEN
    RETURN NULL;
  END IF;

  digits := regexp_replace(raw, '\D', '', 'g');

  IF digits = '' THEN
    RETURN NULL;
  END IF;

  IF left(digits, 3) = '234' AND length(digits) = 13 THEN
    RETURN '+' || digits;
  END IF;

  IF left(digits, 1) = '0' AND length(digits) = 11 THEN
    RETURN '+234' || substring(digits from 2);
  END IF;

  IF length(digits) = 10 THEN
    RETURN '+234' || digits;
  END IF;

  IF left(digits, 1) <> '0' AND left(digits, 3) <> '234' AND length(digits) >= 8 THEN
    RETURN '+' || digits;
  END IF;

  RETURN NULL;
END;
$$;

ALTER TABLE public.customers
  ADD COLUMN IF NOT EXISTS normalized_phone text,
  ADD COLUMN IF NOT EXISTS merged_into uuid REFERENCES public.customers(id) ON DELETE SET NULL;

CREATE OR REPLACE FUNCTION public.sync_customer_normalized_phone()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.normalized_phone := public.normalize_customer_phone(coalesce(NEW.phone, NEW.phone_number));
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_sync_customer_normalized_phone ON public.customers;
CREATE TRIGGER trg_sync_customer_normalized_phone
BEFORE INSERT OR UPDATE OF phone, phone_number
ON public.customers
FOR EACH ROW
EXECUTE FUNCTION public.sync_customer_normalized_phone();

UPDATE public.customers
SET normalized_phone = public.normalize_customer_phone(coalesce(phone, phone_number))
WHERE normalized_phone IS DISTINCT FROM public.normalize_customer_phone(coalesce(phone, phone_number));

CREATE INDEX IF NOT EXISTS idx_customers_norm_phone
  ON public.customers (tenant_id, normalized_phone)
  WHERE merged_into IS NULL AND normalized_phone IS NOT NULL;

ALTER TABLE public.customer_profile_summary
  ADD COLUMN IF NOT EXISTS lifetime_value_cents bigint NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS avg_spend_cents bigint NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS outstanding_balance_cents bigint NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS repeat_interval_days integer,
  ADD COLUMN IF NOT EXISTS preferred_staff_id uuid,
  ADD COLUMN IF NOT EXISTS no_show_count integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cancellation_count integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS last_computed_at timestamptz;

CREATE TABLE IF NOT EXISTS public.customer_merge_candidates (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  customer_a uuid NOT NULL REFERENCES public.customers(id) ON DELETE CASCADE,
  customer_b uuid NOT NULL REFERENCES public.customers(id) ON DELETE CASCADE,
  score numeric NOT NULL,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'merged', 'dismissed')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  merged_at timestamptz,
  dismissed_at timestamptz,
  merged_by uuid,
  dismissed_by uuid,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT customer_merge_candidates_distinct_pair CHECK (customer_a <> customer_b)
);

CREATE UNIQUE INDEX IF NOT EXISTS customer_merge_candidates_unique_pair
  ON public.customer_merge_candidates (
    tenant_id,
    LEAST(customer_a, customer_b),
    GREATEST(customer_a, customer_b)
  );

CREATE INDEX IF NOT EXISTS customer_merge_candidates_tenant_status
  ON public.customer_merge_candidates (tenant_id, status, score DESC, created_at DESC);

CREATE OR REPLACE FUNCTION public.merge_customers_tx(
  p_tenant_id uuid,
  p_survivor_id uuid,
  p_loser_id uuid
)
RETURNS TABLE (survivor_id uuid, loser_id uuid)
LANGUAGE plpgsql
AS $$
DECLARE
  survivor public.customers%ROWTYPE;
  loser public.customers%ROWTYPE;
  merged_notes text;
  merged_tags text[];
BEGIN
  IF p_survivor_id = p_loser_id THEN
    RAISE EXCEPTION 'survivor and loser must be different customers';
  END IF;

  SELECT * INTO survivor
  FROM public.customers
  WHERE tenant_id = p_tenant_id
    AND id = p_survivor_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'survivor customer not found';
  END IF;

  SELECT * INTO loser
  FROM public.customers
  WHERE tenant_id = p_tenant_id
    AND id = p_loser_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'loser customer not found';
  END IF;

  IF loser.merged_into IS NOT NULL THEN
    RAISE EXCEPTION 'loser customer already merged';
  END IF;

  merged_notes := CASE
    WHEN coalesce(survivor.notes, '') = '' THEN loser.notes
    WHEN coalesce(loser.notes, '') = '' THEN survivor.notes
    ELSE survivor.notes || E'\n--- merged customer notes ---\n' || loser.notes
  END;

  merged_tags := ARRAY(
    SELECT DISTINCT tag
    FROM unnest(coalesce(survivor.tags, '{}'::text[]) || coalesce(loser.tags, '{}'::text[])) AS tag
    WHERE tag IS NOT NULL AND btrim(tag) <> ''
  );

  UPDATE public.reservations
  SET customer_id = p_survivor_id
  WHERE tenant_id = p_tenant_id
    AND customer_id = p_loser_id;

  UPDATE public.retail_orders
  SET customer_id = p_survivor_id
  WHERE tenant_id = p_tenant_id
    AND customer_id = p_loser_id;

  UPDATE public.chats
  SET customer_id = p_survivor_id
  WHERE tenant_id = p_tenant_id
    AND customer_id = p_loser_id;

  UPDATE public.reviews
  SET customer_id = p_survivor_id
  WHERE tenant_id = p_tenant_id
    AND customer_id = p_loser_id;

  UPDATE public.analytics_events
  SET customer_id = p_survivor_id
  WHERE tenant_id = p_tenant_id
    AND customer_id = p_loser_id;

  UPDATE public.reservation_services
  SET customer_id = p_survivor_id
  WHERE tenant_id = p_tenant_id
    AND customer_id = p_loser_id;

  UPDATE public.customer_analytics
  SET customer_id = p_survivor_id
  WHERE tenant_id = p_tenant_id
    AND customer_id = p_loser_id;

  UPDATE public.sias_outcome_attributions
  SET customer_id = p_survivor_id
  WHERE tenant_id = p_tenant_id
    AND customer_id = p_loser_id;

  UPDATE public.sias_campaign_runs
  SET target_customer_id = p_survivor_id
  WHERE tenant_id = p_tenant_id
    AND target_customer_id = p_loser_id;

  DELETE FROM public.customer_profile_summary
  WHERE tenant_id = p_tenant_id
    AND customer_id = p_loser_id;

  UPDATE public.customers
  SET notes = merged_notes,
      tags = coalesce(merged_tags, '{}'::text[]),
      name = coalesce(name, loser.name, loser.customer_name),
      customer_name = coalesce(customer_name, loser.customer_name, loser.name),
      email = coalesce(email, loser.email),
      phone = coalesce(phone, loser.phone, loser.phone_number),
      phone_number = coalesce(phone_number, loser.phone_number, loser.phone),
      normalized_phone = coalesce(normalized_phone, loser.normalized_phone),
      updated_at = now()
  WHERE tenant_id = p_tenant_id
    AND id = p_survivor_id;

  UPDATE public.customers
  SET merged_into = p_survivor_id,
      updated_at = now()
  WHERE tenant_id = p_tenant_id
    AND id = p_loser_id;

  UPDATE public.customer_merge_candidates
  SET status = 'merged',
      merged_at = now(),
      updated_at = now()
  WHERE tenant_id = p_tenant_id
    AND (
      (customer_a = p_survivor_id AND customer_b = p_loser_id)
      OR (customer_a = p_loser_id AND customer_b = p_survivor_id)
    );

  survivor_id := p_survivor_id;
  loser_id := p_loser_id;
  RETURN NEXT;
END;
$$;

ALTER TABLE public.customer_merge_candidates ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS customer_merge_candidates_service_role ON public.customer_merge_candidates;
CREATE POLICY customer_merge_candidates_service_role
  ON public.customer_merge_candidates
  AS PERMISSIVE
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

GRANT EXECUTE ON FUNCTION public.merge_customers_tx(uuid, uuid, uuid) TO service_role;

COMMIT;
-- END db/migrations/133_customer_memory.sql

-- BEGIN db/migrations/134_multimodal_capture.sql
CREATE TABLE IF NOT EXISTS public.media_inputs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  source text NOT NULL CHECK (source IN ('whatsapp', 'dashboard', 'api')),
  kind text NOT NULL CHECK (kind IN ('receipt', 'invoice', 'voice', 'photo', 'pdf', 'stock_sheet', 'screenshot', 'service_note')),
  storage_path text NOT NULL,
  file_hash text NOT NULL,
  mime text NOT NULL,
  size bigint NOT NULL DEFAULT 0 CHECK (size >= 0),
  uploaded_by uuid NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_media_inputs_tenant_hash_path
  ON public.media_inputs (tenant_id, file_hash, storage_path);

CREATE INDEX IF NOT EXISTS idx_media_inputs_tenant_hash
  ON public.media_inputs (tenant_id, file_hash);

CREATE TABLE IF NOT EXISTS public.extraction_jobs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  media_input_id uuid NOT NULL REFERENCES public.media_inputs(id) ON DELETE CASCADE,
  status text NOT NULL CHECK (status IN ('pending', 'processing', 'review_required', 'confirmed', 'failed')) DEFAULT 'pending',
  model text NULL,
  prompt_version text NULL,
  error text NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_extraction_jobs_tenant_status
  ON public.extraction_jobs (tenant_id, status, created_at DESC);

CREATE TABLE IF NOT EXISTS public.extracted_records (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  job_id uuid NOT NULL REFERENCES public.extraction_jobs(id) ON DELETE CASCADE,
  record_type text NOT NULL CHECK (record_type IN ('expense', 'purchase', 'stock_receipt', 'supplier_payment', 'retail_sale', 'service', 'stock_count')),
  fields jsonb NOT NULL DEFAULT '{}'::jsonb,
  field_confidence jsonb NOT NULL DEFAULT '{}'::jsonb,
  low_confidence_fields text[] NOT NULL DEFAULT '{}'::text[],
  proposed_action jsonb NULL,
  linked_record_type text NULL,
  linked_record_id uuid NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_extracted_records_tenant_type
  ON public.extracted_records (tenant_id, record_type, created_at DESC);

CREATE TABLE IF NOT EXISTS public.suppliers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  name text NOT NULL,
  phone text NULL,
  email text NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_suppliers_tenant_name
  ON public.suppliers (tenant_id, lower(name));

CREATE TABLE IF NOT EXISTS public.expenses (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  supplier_id uuid NULL REFERENCES public.suppliers(id) ON DELETE SET NULL,
  media_input_id uuid NULL REFERENCES public.media_inputs(id) ON DELETE SET NULL,
  amount_cents bigint NOT NULL CHECK (amount_cents >= 0),
  currency text NOT NULL DEFAULT 'NGN',
  expense_date date NOT NULL,
  reference text NULL,
  notes text NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_expenses_tenant_date
  ON public.expenses (tenant_id, expense_date DESC);

CREATE TABLE IF NOT EXISTS public.purchases (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  supplier_id uuid NULL REFERENCES public.suppliers(id) ON DELETE SET NULL,
  media_input_id uuid NULL REFERENCES public.media_inputs(id) ON DELETE SET NULL,
  total_cents bigint NOT NULL CHECK (total_cents >= 0),
  currency text NOT NULL DEFAULT 'NGN',
  purchase_date date NOT NULL,
  reference text NULL,
  status text NOT NULL DEFAULT 'recorded' CHECK (status IN ('recorded', 'received', 'cancelled')),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_purchases_tenant_date
  ON public.purchases (tenant_id, purchase_date DESC);

CREATE TABLE IF NOT EXISTS public.supplier_payments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  supplier_id uuid NULL REFERENCES public.suppliers(id) ON DELETE SET NULL,
  purchase_id uuid NULL REFERENCES public.purchases(id) ON DELETE SET NULL,
  media_input_id uuid NULL REFERENCES public.media_inputs(id) ON DELETE SET NULL,
  amount_cents bigint NOT NULL CHECK (amount_cents >= 0),
  currency text NOT NULL DEFAULT 'NGN',
  payment_date date NOT NULL,
  reference text NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_supplier_payments_tenant_date
  ON public.supplier_payments (tenant_id, payment_date DESC);

CREATE TABLE IF NOT EXISTS public.stock_receipts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  purchase_id uuid NULL REFERENCES public.purchases(id) ON DELETE SET NULL,
  media_input_id uuid NULL REFERENCES public.media_inputs(id) ON DELETE SET NULL,
  supplier_id uuid NULL REFERENCES public.suppliers(id) ON DELETE SET NULL,
  received_at timestamptz NOT NULL DEFAULT now(),
  notes text NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.media_inputs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.extraction_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.extracted_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.suppliers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.purchases ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.supplier_payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_receipts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS media_inputs_service_role ON public.media_inputs;
CREATE POLICY media_inputs_service_role ON public.media_inputs
  AS PERMISSIVE FOR ALL TO service_role USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS extraction_jobs_service_role ON public.extraction_jobs;
CREATE POLICY extraction_jobs_service_role ON public.extraction_jobs
  AS PERMISSIVE FOR ALL TO service_role USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS extracted_records_service_role ON public.extracted_records;
CREATE POLICY extracted_records_service_role ON public.extracted_records
  AS PERMISSIVE FOR ALL TO service_role USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS suppliers_service_role ON public.suppliers;
CREATE POLICY suppliers_service_role ON public.suppliers
  AS PERMISSIVE FOR ALL TO service_role USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS expenses_service_role ON public.expenses;
CREATE POLICY expenses_service_role ON public.expenses
  AS PERMISSIVE FOR ALL TO service_role USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS purchases_service_role ON public.purchases;
CREATE POLICY purchases_service_role ON public.purchases
  AS PERMISSIVE FOR ALL TO service_role USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS supplier_payments_service_role ON public.supplier_payments;
CREATE POLICY supplier_payments_service_role ON public.supplier_payments
  AS PERMISSIVE FOR ALL TO service_role USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS stock_receipts_service_role ON public.stock_receipts;
CREATE POLICY stock_receipts_service_role ON public.stock_receipts
  AS PERMISSIVE FOR ALL TO service_role USING (true) WITH CHECK (true);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.media_inputs TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.extraction_jobs TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.extracted_records TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.suppliers TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.expenses TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.purchases TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.supplier_payments TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.stock_receipts TO service_role;
-- END db/migrations/134_multimodal_capture.sql

-- BEGIN db/migrations/135_analytics_briefings.sql
CREATE TABLE IF NOT EXISTS public.analytics_query_log (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  actor_id uuid NULL,
  question text NOT NULL,
  metric_key text NOT NULL,
  params jsonb NOT NULL DEFAULT '{}'::jsonb,
  row_count integer NOT NULL DEFAULT 0 CHECK (row_count >= 0),
  latency_ms integer NOT NULL DEFAULT 0 CHECK (latency_ms >= 0),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_analytics_query_log_tenant_created
  ON public.analytics_query_log (tenant_id, created_at DESC);

CREATE TABLE IF NOT EXISTS public.briefing_schedules (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  briefing_type text NOT NULL CHECK (briefing_type IN ('morning', 'weekly')),
  schedule_time time NOT NULL,
  enabled boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, briefing_type)
);

CREATE TABLE IF NOT EXISTS public.briefing_runs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  briefing_type text NOT NULL CHECK (briefing_type IN ('morning', 'weekly')),
  status text NOT NULL CHECK (status IN ('sent', 'skipped', 'failed')) DEFAULT 'sent',
  body text NOT NULL DEFAULT '',
  meta jsonb NOT NULL DEFAULT '{}'::jsonb,
  sent_at timestamptz NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_briefing_runs_tenant_created
  ON public.briefing_runs (tenant_id, created_at DESC);

ALTER TABLE public.analytics_query_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.briefing_schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.briefing_runs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS analytics_query_log_service_role ON public.analytics_query_log;
CREATE POLICY analytics_query_log_service_role ON public.analytics_query_log
  AS PERMISSIVE FOR ALL TO service_role USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS briefing_schedules_service_role ON public.briefing_schedules;
CREATE POLICY briefing_schedules_service_role ON public.briefing_schedules
  AS PERMISSIVE FOR ALL TO service_role USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS briefing_runs_service_role ON public.briefing_runs;
CREATE POLICY briefing_runs_service_role ON public.briefing_runs
  AS PERMISSIVE FOR ALL TO service_role USING (true) WITH CHECK (true);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.analytics_query_log TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.briefing_schedules TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.briefing_runs TO service_role;
-- END db/migrations/135_analytics_briefings.sql

-- BEGIN db/migrations/136_recommendations.sql
CREATE TABLE IF NOT EXISTS public.business_recommendations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  type text NOT NULL,
  title text NOT NULL,
  reason text NOT NULL,
  recommended_action text NOT NULL,
  basis jsonb NOT NULL DEFAULT '{}'::jsonb,
  estimated_impact jsonb,
  confidence numeric,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'dismissed', 'snoozed', 'expired')),
  snooze_until timestamptz,
  entity_type text,
  entity_id uuid,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.recommendation_outcomes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  recommendation_id uuid NOT NULL REFERENCES public.business_recommendations(id) ON DELETE CASCADE,
  outcome text NOT NULL CHECK (outcome IN ('acted', 'ignored', 'expired')),
  observed_effect jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_business_recommendations_pending_unique
  ON public.business_recommendations (tenant_id, type, entity_type, entity_id)
  WHERE status = 'pending' AND entity_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_business_recommendations_tenant_status
  ON public.business_recommendations (tenant_id, status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_recommendation_outcomes_recommendation
  ON public.recommendation_outcomes (recommendation_id, created_at DESC);

ALTER TABLE public.business_recommendations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.recommendation_outcomes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS business_recommendations_service_role ON public.business_recommendations;
CREATE POLICY business_recommendations_service_role
  ON public.business_recommendations
  AS PERMISSIVE
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

DROP POLICY IF EXISTS recommendation_outcomes_service_role ON public.recommendation_outcomes;
CREATE POLICY recommendation_outcomes_service_role
  ON public.recommendation_outcomes
  AS PERMISSIVE
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
-- END db/migrations/136_recommendations.sql

-- BEGIN db/migrations/137_fix_update_inventory_overload.sql
BEGIN;

-- Fix an ambiguous-overload bug that breaks every inventory-tracked retail sale
-- and refund at runtime.
--
-- Migration 130 added public.update_inventory(..., p_location_id uuid) as a NEW
-- overload. CREATE OR REPLACE only replaces a function with an IDENTICAL argument
-- signature, so adding p_location_id did not replace the 10-argument version from
-- migration 126 — it created a second function. A 10-argument call, as made by
-- record_retail_sale_tx and refund_retail_sale_tx (migration 127):
--
--     PERFORM public.update_inventory(tenant, product, variant, -qty, 'sale',
--             'retail_order', order_id::text, reason, actor, NULL);
--
-- then matches BOTH the 10-arg and the 11-arg overloads (the latter via its
-- p_location_id default), producing:
--
--     ERROR: function public.update_inventory(uuid, uuid, uuid, integer, ...,
--            uuid, unknown) is not unique
--
-- i.e. no POS/retail sale or refund can record inventory. Caught by the live
-- money-path smoke (tests/live-smoke/money-paths-live.smoke.test.ts).
--
-- Fix: drop the superseded 10-argument overload. The 11-argument version
-- (p_location_id DEFAULT NULL, migration 130) already handles 10-argument callers
-- via the default, so every existing call site keeps working and now resolves to a
-- single, unambiguous function.

DROP FUNCTION IF EXISTS public.update_inventory(
  uuid, uuid, uuid, integer, text, text, text, text, uuid, integer
);

COMMIT;
-- END db/migrations/137_fix_update_inventory_overload.sql

-- BEGIN db/migrations/138_harden_retail_sale_functions.sql
-- Hardening for the SECURITY DEFINER retail-sale functions introduced in 127.
-- PostgreSQL grants function EXECUTE to PUBLIC by default; these privileged
-- functions must only be callable by Booka's server-side service role.
BEGIN;

ALTER FUNCTION public.record_retail_sale_tx(uuid, uuid, jsonb, uuid, text, uuid, text, text, text, jsonb)
  SET search_path = pg_catalog, public;
ALTER FUNCTION public.refund_retail_sale_tx(uuid, uuid, uuid, text, text)
  SET search_path = pg_catalog, public;

REVOKE ALL ON FUNCTION public.record_retail_sale_tx(uuid, uuid, jsonb, uuid, text, uuid, text, text, text, jsonb)
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.refund_retail_sale_tx(uuid, uuid, uuid, text, text)
  FROM PUBLIC, anon, authenticated;

GRANT EXECUTE ON FUNCTION public.record_retail_sale_tx(uuid, uuid, jsonb, uuid, text, uuid, text, text, text, jsonb)
  TO service_role;
GRANT EXECUTE ON FUNCTION public.refund_retail_sale_tx(uuid, uuid, uuid, text, text)
  TO service_role;

COMMIT;
-- END db/migrations/138_harden_retail_sale_functions.sql

-- BEGIN db/migrations/2026-07-31_add_reservations_source.sql
-- Migration: add reservations.source (text)
-- Date: 2026-07-31
--
-- WHY: the public booking path (createPublicBooking) records where a booking
-- came from with `.insert({ ..., source: 'public_booking' })`, but `reservations`
-- has no `source` column on live — the insert errored, so public-page bookings
-- silently failed. Rather than route the origin through metadata only, add the
-- column (useful for booking-origin analytics, parallel to customers.source).
--
-- SAFETY: idempotent (ADD COLUMN IF NOT EXISTS), non-destructive, no RLS change.
-- Backfills existing rows from metadata.booking_source when present. Reviewer
-- runs this; validated in a throwaway postgres:16-alpine container.

BEGIN;

ALTER TABLE public.reservations
  ADD COLUMN IF NOT EXISTS source text;

-- Backfill origin for rows that captured it in metadata while the column was
-- absent. Only where source is still NULL, so re-runs never overwrite.
UPDATE public.reservations
SET source = metadata->>'booking_source'
WHERE source IS NULL
  AND metadata ? 'booking_source'
  AND jsonb_typeof(metadata->'booking_source') = 'string';

COMMIT;

-- Rollback (manual, NOT run automatically):
--   ALTER TABLE public.reservations DROP COLUMN IF EXISTS source;
-- END db/migrations/2026-07-31_add_reservations_source.sql

-- BEGIN db/migrations/2026-08-04_meta_embedded_signup_foundation.sql
-- Meta WhatsApp Embedded Signup foundation
--
-- This migration is additive. It prepares Booka for tenant-owned WABAs and
-- phone numbers connected either through the current operator-assisted Direct
-- Cloud API path or the future Meta Embedded Signup path.
--
-- IMPORTANT:
-- - Do not put raw Meta access tokens in whatsapp_configurations.
-- - New Meta tokens should be stored encrypted in whatsapp_provider_secrets.
-- - Existing api_key values are deliberately not transformed here: encryption
--   must happen in application code using the server-only ENCRYPTION_KEY.

BEGIN;

-- 1. Tenant connection lifecycle. These columns contain identifiers and state,
-- never a Meta access token or payment-card information.
ALTER TABLE public.whatsapp_configurations
  ADD COLUMN IF NOT EXISTS meta_connection_source TEXT,
  ADD COLUMN IF NOT EXISTS meta_connection_status TEXT,
  ADD COLUMN IF NOT EXISTS meta_billing_owner TEXT,
  ADD COLUMN IF NOT EXISTS meta_connected_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS meta_disconnected_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS meta_webhook_subscribed_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS meta_last_validated_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS meta_last_error TEXT;

ALTER TABLE public.whatsapp_configurations
  DROP CONSTRAINT IF EXISTS whatsapp_configurations_meta_connection_source_check,
  ADD CONSTRAINT whatsapp_configurations_meta_connection_source_check
    CHECK (meta_connection_source IS NULL OR meta_connection_source IN ('direct', 'embedded_signup')),
  DROP CONSTRAINT IF EXISTS whatsapp_configurations_meta_connection_status_check,
  ADD CONSTRAINT whatsapp_configurations_meta_connection_status_check
    CHECK (meta_connection_status IS NULL OR meta_connection_status IN (
      'pending', 'connected', 'action_required', 'disconnected', 'revoked', 'failed'
    )),
  DROP CONSTRAINT IF EXISTS whatsapp_configurations_meta_billing_owner_check,
  ADD CONSTRAINT whatsapp_configurations_meta_billing_owner_check
    CHECK (meta_billing_owner IS NULL OR meta_billing_owner IN ('client', 'booka'));

-- Existing active Meta mappings are known operator-assisted connections.
UPDATE public.whatsapp_configurations
SET
  meta_connection_source = COALESCE(meta_connection_source, 'direct'),
  meta_connection_status = COALESCE(meta_connection_status, 'connected'),
  meta_billing_owner = COALESCE(meta_billing_owner, 'client'),
  meta_connected_at = COALESCE(meta_connected_at, updated_at, created_at, NOW())
WHERE provider = 'meta'
  AND active = true
  AND meta_phone_number_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_whatsapp_configurations_meta_connection_status
  ON public.whatsapp_configurations (meta_connection_status)
  WHERE provider = 'meta';

-- 2. Encrypted Meta credential envelope. `api_key` remains nullable only for
-- encrypted rows and legacy rows; application code must prefer encrypted_api_key.
ALTER TABLE public.whatsapp_provider_secrets
  ALTER COLUMN api_key DROP NOT NULL,
  ADD COLUMN IF NOT EXISTS encrypted_api_key TEXT,
  ADD COLUMN IF NOT EXISTS encryption_iv TEXT,
  ADD COLUMN IF NOT EXISTS encryption_key_version TEXT,
  ADD COLUMN IF NOT EXISTS token_scopes JSONB NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS last_validated_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS revoked_at TIMESTAMPTZ;

ALTER TABLE public.whatsapp_provider_secrets
  DROP CONSTRAINT IF EXISTS whatsapp_provider_secrets_encrypted_key_check,
  ADD CONSTRAINT whatsapp_provider_secrets_encrypted_key_check
    CHECK (
      (encrypted_api_key IS NULL AND encryption_iv IS NULL AND encryption_key_version IS NULL)
      OR
      (encrypted_api_key IS NOT NULL AND encryption_iv IS NOT NULL AND encryption_key_version IS NOT NULL)
    );

-- 3. Append-only, token-free audit trail for provisioning and disconnection.
CREATE TABLE IF NOT EXISTS public.tenant_meta_connection_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  event_type TEXT NOT NULL CHECK (event_type IN (
    'connection_started', 'connection_connected', 'connection_failed',
    'webhook_subscribed', 'credential_rotated', 'connection_disconnected',
    'connection_revoked', 'validation_failed'
  )),
  connection_source TEXT CHECK (connection_source IN ('direct', 'embedded_signup')),
  actor_user_id UUID,
  meta_waba_id TEXT,
  meta_phone_number_id TEXT,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT tenant_meta_connection_events_no_credentials
    CHECK (NOT (metadata ? 'access_token') AND NOT (metadata ? 'api_key'))
);

CREATE INDEX IF NOT EXISTS idx_tenant_meta_connection_events_tenant_created
  ON public.tenant_meta_connection_events (tenant_id, created_at DESC);

ALTER TABLE public.tenant_meta_connection_events ENABLE ROW LEVEL SECURITY;

-- This is a server-only audit table. Tenant owners receive a redacted status
-- through Booka API routes; they must never read credentials or raw Meta events.
REVOKE ALL ON TABLE public.tenant_meta_connection_events FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.tenant_meta_connection_events TO service_role;

COMMIT;
-- END db/migrations/2026-08-04_meta_embedded_signup_foundation.sql

-- BEGIN db/migrations/2026-08-10_storefront_engine.sql
-- Public Storefront Engine: queryable campaigns + privacy-minimised funnel events.
CREATE TABLE IF NOT EXISTS public.storefront_campaigns (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','approved','active','paused','expired','superseded')),
  title text NOT NULL, copy text, cta_label text, target_type text, target_ids jsonb NOT NULL DEFAULT '[]'::jsonb,
  start_at timestamptz NOT NULL DEFAULT now(), end_at timestamptz, source text NOT NULL DEFAULT 'owner', approval_metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CHECK (end_at IS NULL OR end_at > start_at)
);
CREATE INDEX IF NOT EXISTS idx_storefront_campaigns_active ON public.storefront_campaigns (tenant_id, status, start_at DESC);
CREATE TABLE IF NOT EXISTS public.storefront_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  event_type text NOT NULL CHECK (event_type IN ('storefront_view','service_view','product_view','cta_click','ask_booka_opened','booking_started','booking_completed','product_added','checkout_started','purchase_completed','campaign_view','campaign_conversion')),
  page_type text NOT NULL CHECK (page_type IN ('storefront','service','product','campaign')), session_id uuid, service_id uuid REFERENCES public.services(id) ON DELETE SET NULL, product_id uuid REFERENCES public.products(id) ON DELETE SET NULL, campaign_id uuid REFERENCES public.storefront_campaigns(id) ON DELETE SET NULL,
  referrer text, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_storefront_events_funnel ON public.storefront_events (tenant_id, event_type, created_at DESC);
ALTER TABLE public.storefront_campaigns ENABLE ROW LEVEL SECURITY; ALTER TABLE public.storefront_events ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS storefront_campaigns_tenant_access ON public.storefront_campaigns; CREATE POLICY storefront_campaigns_tenant_access ON public.storefront_campaigns FOR ALL USING (tenant_id IN (SELECT tenant_id FROM public.tenant_users WHERE user_id = auth.uid()));
DROP POLICY IF EXISTS storefront_events_tenant_access ON public.storefront_events; CREATE POLICY storefront_events_tenant_access ON public.storefront_events FOR SELECT USING (tenant_id IN (SELECT tenant_id FROM public.tenant_users WHERE user_id = auth.uid()));
-- END db/migrations/2026-08-10_storefront_engine.sql