-- Booka staging WhatsApp message metering migrations — fresh schema only
-- Generated by scripts/generate-staging-sql-editor-release.mjs.
-- Run only against the intended staging Supabase database after backup/preflight.
-- Guard: migrations 139-143 must not be partially or fully present.
DO $$
DECLARE existing_objects integer;
BEGIN
  SELECT count(*) INTO existing_objects
  FROM (VALUES
    ((SELECT 1 FROM information_schema.columns
      WHERE table_schema = 'public' AND table_name = 'ai_wallets' AND column_name = 'message_rate_credits')::text),
    ((SELECT 1 FROM information_schema.columns
      WHERE table_schema = 'public' AND table_name = 'ai_wallet_ledger' AND column_name = 'meter')::text),
    (to_regclass('public.whatsapp_message_charges')::text),
    (to_regprocedure('public.reserve_ai_wallet_spend(uuid,numeric,text,text,text,text,jsonb,numeric,text)')::text),
    ((SELECT 1 FROM information_schema.columns
      WHERE table_schema = 'public' AND table_name = 'ai_wallets' AND column_name = 'message_handoff_warned_on')::text)
  ) AS objects(object_name)
  WHERE object_name IS NOT NULL;

  IF existing_objects <> 0 THEN
    RAISE EXCEPTION 'WhatsApp metering schema is present or partial (% objects). Do not replay 139-143.', existing_objects;
  END IF;
END;
$$;

-- BEGIN db/migrations/139_whatsapp_metering_wallet.sql
-- Migration 139: WhatsApp metering — meter dimension and wallet knobs
-- Extends the existing AI wallet so a single tenant balance funds two meters
-- (LLM tokens and WhatsApp messages) without duplicating reserve/settle logic.

ALTER TABLE public.ai_wallets
  ADD COLUMN IF NOT EXISTS message_rate_credits NUMERIC(20,6),
  ADD COLUMN IF NOT EXISTS grace_overdraft_credits NUMERIC(20,6) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS auto_recharge_enabled BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS auto_recharge_threshold_credits NUMERIC(20,6),
  ADD COLUMN IF NOT EXISTS auto_recharge_amount_credits NUMERIC(20,6);

COMMENT ON COLUMN public.ai_wallets.message_rate_credits IS
  'Per-tenant override for the WhatsApp message sell rate. NULL = platform default.';
COMMENT ON COLUMN public.ai_wallets.grace_overdraft_credits IS
  'How far below zero this wallet may go for message sends before handoff.';

ALTER TABLE public.ai_wallet_ledger
  ADD COLUMN IF NOT EXISTS meter TEXT NOT NULL DEFAULT 'llm';

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'ai_wallet_ledger_meter_check'
  ) THEN
    ALTER TABLE public.ai_wallet_ledger
      ADD CONSTRAINT ai_wallet_ledger_meter_check
      CHECK (meter IN ('llm', 'whatsapp'));
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_ai_wallet_ledger_tenant_meter_created_at
  ON public.ai_wallet_ledger (tenant_id, meter, created_at DESC);
-- END db/migrations/139_whatsapp_metering_wallet.sql

-- BEGIN db/migrations/140_whatsapp_message_charges.sql
-- Migration 140: WhatsApp message charges
-- Correlates a Meta wamid to the wallet reservation taken before the send, so
-- settlement can charge from Meta's own pricing object and undelivered
-- messages can be released instead of billed.

CREATE TABLE IF NOT EXISTS public.whatsapp_message_charges (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  provider TEXT NOT NULL,
  wamid TEXT,
  wallet_reservation_id UUID,
  reserved_credits NUMERIC(20,6) NOT NULL DEFAULT 0,
  settled_credits NUMERIC(20,6),
  status TEXT NOT NULL DEFAULT 'reserved'
    CHECK (status IN ('reserved', 'settled', 'released', 'failed')),
  billable BOOLEAN,
  pricing_category TEXT,
  pricing_type TEXT,
  pricing_model TEXT,
  delivery_status TEXT,
  message_kind TEXT,
  mode TEXT NOT NULL DEFAULT 'live'
    CHECK (mode IN ('shadow', 'live')),
  attribution JSONB NOT NULL DEFAULT '{}'::jsonb,
  sent_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  settled_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_whatsapp_message_charges_tenant_wamid
  ON public.whatsapp_message_charges (tenant_id, wamid) WHERE wamid IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_whatsapp_message_charges_sweeper
  ON public.whatsapp_message_charges (sent_at) WHERE status = 'reserved';

CREATE INDEX IF NOT EXISTS idx_whatsapp_message_charges_tenant_sent_at
  ON public.whatsapp_message_charges (tenant_id, sent_at DESC);

ALTER TABLE public.whatsapp_message_charges ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS whatsapp_message_charges_service_role
  ON public.whatsapp_message_charges;
CREATE POLICY whatsapp_message_charges_service_role
  ON public.whatsapp_message_charges
  AS PERMISSIVE FOR ALL TO service_role USING (true) WITH CHECK (true);

COMMENT ON COLUMN public.whatsapp_message_charges.attribution IS
  'Free-form {conversation_id, booking_id, flow, ai_layer} used by cost reporting.';
COMMENT ON COLUMN public.whatsapp_message_charges.mode IS
  'shadow rows record volume but never move money; live rows are real revenue.';
-- END db/migrations/140_whatsapp_message_charges.sql

-- BEGIN db/migrations/141_overdraft_reservation.sql
-- Migration 141: overdraft-aware wallet reservation with a meter dimension
-- The pre-141 reservation hard-fails on insufficient balance. Message sends
-- need a bounded grace overdraft so an empty wallet degrades loudly instead of
-- going silent mid-conversation.

-- The old signatures must be dropped explicitly. Leaving them in place creates
-- an overload that makes Supabase's named-parameter RPC resolution ambiguous at
-- runtime rather than at deploy time.

-- `#variable_conflict use_column` is required in both bodies below: RETURNS
-- TABLE(..., balance_credits, ...) declares an implicit OUT variable named
-- balance_credits that collides with ai_wallets.balance_credits. Without this
-- pragma, `UPDATE ai_wallets SET balance_credits = balance_credits - x` throws
-- "column reference \"balance_credits\" is ambiguous" under Postgres's default
-- variable_conflict=error — this is a real bug already present (unfixed) in
-- reserve_ai_wallet_spend/settle_ai_wallet_spend as shipped in 077_ai_wallets.sql,
-- confirmed by executing them against a fresh postgres:16-alpine container.
DROP FUNCTION IF EXISTS public.reserve_ai_wallet_spend(UUID, NUMERIC, TEXT, TEXT, TEXT, TEXT, JSONB);
DROP FUNCTION IF EXISTS public.settle_ai_wallet_spend(UUID, UUID, NUMERIC, NUMERIC, BIGINT, TEXT, TEXT, TEXT, JSONB);

CREATE OR REPLACE FUNCTION public.reserve_ai_wallet_spend(
  p_tenant_id UUID,
  p_amount_credits NUMERIC,
  p_request_id TEXT DEFAULT NULL,
  p_provider TEXT DEFAULT NULL,
  p_model TEXT DEFAULT NULL,
  p_description TEXT DEFAULT NULL,
  p_metadata JSONB DEFAULT '{}'::jsonb,
  p_allow_overdraft_credits NUMERIC DEFAULT 0,
  p_meter TEXT DEFAULT 'llm'
)
RETURNS TABLE (
  allowed BOOLEAN,
  balance_credits NUMERIC,
  reservation_id UUID,
  reason TEXT
)
LANGUAGE plpgsql
SET search_path = public, pg_temp
AS $$
#variable_conflict use_column
DECLARE
  wallet public.ai_wallets;
  new_ledger_id UUID;
  overdraft NUMERIC;
BEGIN
  PERFORM public.ensure_ai_wallet(p_tenant_id);

  IF p_amount_credits IS NULL OR p_amount_credits <= 0 THEN
    RETURN QUERY SELECT false, NULL::NUMERIC, NULL::UUID, 'invalid_amount';
    RETURN;
  END IF;

  SELECT * INTO wallet
  FROM public.ai_wallets
  WHERE tenant_id = p_tenant_id
  FOR UPDATE;

  overdraft := LEAST(
    COALESCE(p_allow_overdraft_credits, 0),
    COALESCE(wallet.grace_overdraft_credits, 0)
  );

  IF wallet.balance_credits + overdraft < p_amount_credits THEN
    RETURN QUERY SELECT false, wallet.balance_credits, NULL::UUID, 'insufficient_balance';
    RETURN;
  END IF;

  UPDATE public.ai_wallets
  SET
    balance_credits = balance_credits - p_amount_credits,
    updated_at = NOW()
  WHERE tenant_id = p_tenant_id
  RETURNING * INTO wallet;

  INSERT INTO public.ai_wallet_ledger (
    tenant_id, kind, amount_credits, provider, model,
    request_id, description, metadata, meter
  )
  VALUES (
    p_tenant_id, 'reservation', -p_amount_credits, p_provider, p_model,
    p_request_id, COALESCE(p_description, 'AI spend reservation'),
    COALESCE(p_metadata, '{}'::jsonb), COALESCE(p_meter, 'llm')
  )
  RETURNING id INTO new_ledger_id;

  RETURN QUERY SELECT true, wallet.balance_credits, new_ledger_id,
    CASE WHEN wallet.balance_credits < 0 THEN 'reserved_grace' ELSE 'reserved' END;
END;
$$;

CREATE OR REPLACE FUNCTION public.settle_ai_wallet_spend(
  p_tenant_id UUID,
  p_reservation_id UUID,
  p_estimated_credits NUMERIC,
  p_actual_credits NUMERIC,
  p_tokens BIGINT DEFAULT NULL,
  p_provider TEXT DEFAULT NULL,
  p_model TEXT DEFAULT NULL,
  p_request_id TEXT DEFAULT NULL,
  p_metadata JSONB DEFAULT '{}'::jsonb,
  p_meter TEXT DEFAULT 'llm'
)
RETURNS TABLE (
  allowed BOOLEAN,
  balance_credits NUMERIC,
  settlement_id UUID,
  refund_credits NUMERIC,
  extra_credits NUMERIC,
  reason TEXT
)
LANGUAGE plpgsql
SET search_path = public, pg_temp
AS $$
#variable_conflict use_column
DECLARE
  wallet public.ai_wallets;
  adjustment NUMERIC;
  new_ledger_id UUID;
BEGIN
  PERFORM public.ensure_ai_wallet(p_tenant_id);

  IF p_estimated_credits IS NULL OR p_actual_credits IS NULL THEN
    RETURN QUERY SELECT false, NULL::NUMERIC, NULL::UUID, 0::NUMERIC, 0::NUMERIC, 'invalid_amount';
    RETURN;
  END IF;

  SELECT * INTO wallet
  FROM public.ai_wallets
  WHERE tenant_id = p_tenant_id
  FOR UPDATE;

  adjustment := p_estimated_credits - p_actual_credits;

  IF adjustment < 0 AND wallet.balance_credits < ABS(adjustment) THEN
    RETURN QUERY SELECT false, wallet.balance_credits, NULL::UUID, 0::NUMERIC, ABS(adjustment), 'insufficient_balance_for_settlement';
    RETURN;
  END IF;

  UPDATE public.ai_wallets
  SET
    balance_credits = balance_credits + adjustment,
    lifetime_spent_credits = lifetime_spent_credits + p_actual_credits,
    updated_at = NOW()
  WHERE tenant_id = p_tenant_id
  RETURNING * INTO wallet;

  INSERT INTO public.ai_wallet_ledger (
    tenant_id, kind, amount_credits, token_count, provider, model,
    request_id, reference, description, metadata, meter
  )
  VALUES (
    p_tenant_id,
    CASE WHEN adjustment >= 0 THEN 'refund' ELSE 'usage' END,
    adjustment, p_tokens, p_provider, p_model, p_request_id,
    p_reservation_id::text, 'AI spend settlement',
    COALESCE(p_metadata, '{}'::jsonb), COALESCE(p_meter, 'llm')
  )
  RETURNING id INTO new_ledger_id;

  RETURN QUERY SELECT true, wallet.balance_credits, new_ledger_id,
    GREATEST(adjustment, 0), GREATEST(-adjustment, 0), 'settled';
END;
$$;

REVOKE ALL ON FUNCTION public.reserve_ai_wallet_spend(UUID, NUMERIC, TEXT, TEXT, TEXT, TEXT, JSONB, NUMERIC, TEXT)
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.settle_ai_wallet_spend(UUID, UUID, NUMERIC, NUMERIC, BIGINT, TEXT, TEXT, TEXT, JSONB, TEXT)
  FROM PUBLIC, anon, authenticated;

GRANT EXECUTE ON FUNCTION public.reserve_ai_wallet_spend(UUID, NUMERIC, TEXT, TEXT, TEXT, TEXT, JSONB, NUMERIC, TEXT) TO service_role;
GRANT EXECUTE ON FUNCTION public.settle_ai_wallet_spend(UUID, UUID, NUMERIC, NUMERIC, BIGINT, TEXT, TEXT, TEXT, JSONB, TEXT) TO service_role;
-- END db/migrations/141_overdraft_reservation.sql

-- BEGIN db/migrations/142_fix_topup_ai_wallet_ambiguity.sql
-- Migration 142: fix the pre-existing ambiguous-column bug in topup_ai_wallet
-- RETURNS TABLE(..., balance_credits, ...) declares an implicit OUT variable named
-- balance_credits that collides with ai_wallets.balance_credits. Without the
-- #variable_conflict pragma, `UPDATE ai_wallets SET balance_credits = balance_credits + x`
-- throws "column reference \"balance_credits\" is ambiguous" under Postgres's default
-- variable_conflict=error. This is a real bug already present in topup_ai_wallet as
-- shipped in 077_ai_wallets.sql, confirmed by executing it against a fresh
-- postgres:16-alpine container. topup_ai_wallet has failed on every call since 077
-- shipped, meaning no wallet could ever be credited.

CREATE OR REPLACE FUNCTION public.topup_ai_wallet(
  p_tenant_id UUID,
  p_amount_credits NUMERIC,
  p_reference TEXT DEFAULT NULL,
  p_description TEXT DEFAULT NULL,
  p_metadata JSONB DEFAULT '{}'::jsonb
)
RETURNS TABLE (
  balance_credits NUMERIC,
  lifetime_topups_credits NUMERIC,
  lifetime_spent_credits NUMERIC,
  ledger_id UUID
)
LANGUAGE plpgsql
SET search_path = public, pg_temp
AS $$
#variable_conflict use_column
DECLARE
  wallet public.ai_wallets;
  new_ledger_id UUID;
BEGIN
  PERFORM public.ensure_ai_wallet(p_tenant_id);

  IF p_amount_credits IS NULL OR p_amount_credits <= 0 THEN
    RAISE EXCEPTION 'amount must be greater than zero';
  END IF;

  SELECT * INTO wallet
  FROM public.ai_wallets
  WHERE tenant_id = p_tenant_id
  FOR UPDATE;

  UPDATE public.ai_wallets
  SET
    balance_credits = balance_credits + p_amount_credits,
    lifetime_topups_credits = lifetime_topups_credits + p_amount_credits,
    updated_at = NOW()
  WHERE tenant_id = p_tenant_id
  RETURNING * INTO wallet;

  INSERT INTO public.ai_wallet_ledger (
    tenant_id,
    kind,
    amount_credits,
    reference,
    description,
    metadata
  )
  VALUES (
    p_tenant_id,
    'topup',
    p_amount_credits,
    p_reference,
    COALESCE(p_description, 'Manual top-up'),
    COALESCE(p_metadata, '{}'::jsonb)
  )
  RETURNING id INTO new_ledger_id;

  RETURN QUERY SELECT wallet.balance_credits, wallet.lifetime_topups_credits, wallet.lifetime_spent_credits, new_ledger_id;
END;
$$;

-- SECURITY: Postgres grants EXECUTE to PUBLIC on every new function, and 077
-- never revoked it. Verified in a container: after 077, `anon` and
-- `authenticated` can execute all four wallet functions. That was survivable
-- only because topup_ai_wallet was broken and always raised — this migration
-- fixes it, so without these REVOKEs it would become an anonymously callable
-- RPC that creates wallet credit out of nothing. Migration 141 did the same for
-- reserve/settle; this closes the remaining two.
REVOKE ALL ON FUNCTION public.topup_ai_wallet(UUID, NUMERIC, TEXT, TEXT, JSONB)
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.ensure_ai_wallet(UUID, TEXT)
  FROM PUBLIC, anon, authenticated;

GRANT EXECUTE ON FUNCTION public.topup_ai_wallet(UUID, NUMERIC, TEXT, TEXT, JSONB) TO service_role;
GRANT EXECUTE ON FUNCTION public.ensure_ai_wallet(UUID, TEXT) TO service_role;
-- END db/migrations/142_fix_topup_ai_wallet_ambiguity.sql

-- BEGIN db/migrations/143_message_handoff_warned_on.sql
-- Migration 143: per-tenant-per-day markers for the wallet-exhausted handoff
-- One wallet exhaustion fans out to every live conversation. Without a
-- per-tenant marker the owner gets one notifications row plus one Telegram
-- ping per active customer, so 50 live chats became a 50-message burst.
--
-- Deliberately NOT ai_wallets.budget_warned_on: that column belongs to the
-- spend-cap alerter (src/lib/billing/spendCaps/spendAlerts.ts), and sharing it
-- would let a spend-cap warning silently suppress a wallet-handoff alert.

ALTER TABLE public.ai_wallets
  ADD COLUMN IF NOT EXISTS message_handoff_warned_on DATE,
  ADD COLUMN IF NOT EXISTS message_handoff_unanchored_on DATE;

COMMENT ON COLUMN public.ai_wallets.message_handoff_warned_on IS
  'Last date an owner alert for a wallet-exhausted message handoff was emitted. Caps the alert at one per tenant per day.';
COMMENT ON COLUMN public.ai_wallets.message_handoff_unanchored_on IS
  'Last date a handoff was sent but its per-conversation chats.metadata stamp could not be written. While set to today, further handoffs for this tenant are suppressed, so a broken stamp costs one platform-funded send per tenant per day instead of one per inbound message.';
-- END db/migrations/143_message_handoff_warned_on.sql