-- Booka revenue pilot database release

-- Generated by scripts/generate-booka-revenue-pilot-release.mjs. Do not edit by hand.

-- Paste this complete file into the Supabase SQL Editor and run it once.

begin;

-- Fail before applying changes if the SIAS attribution foundation is absent.
do $$
begin
  if to_regclass('public.sias_outcome_attributions') is null then
    raise exception 'Required table public.sias_outcome_attributions is missing. Apply the SIAS baseline migrations before this Booka revenue pilot bundle.';
  end if;
end
$$;

-- Source: db/migrations/122_booka_revenue_requests.sql
create table if not exists public.booka_revenue_requests (
  id uuid primary key default gen_random_uuid(),
  request_type text not null check (request_type in ('revenue_pilot', 'missed_revenue_report')),
  business_name text not null,
  contact_name text not null,
  email text not null,
  phone text not null,
  vertical text not null check (vertical in ('beauty', 'hospitality', 'clinic', 'other')),
  other_vertical text,
  weekly_enquiry_band text not null check (weekly_enquiry_band in ('under_20', '20_49', '50_99', '100_249', '250_plus')),
  channels text[] not null default '{}',
  average_transaction_value_ngn numeric(14,2),
  current_conversion_band text check (current_conversion_band in ('unknown', 'under_10', '10_24', '25_49', '50_plus')),
  instagram_handle text,
  website_url text,
  consent_to_contact boolean not null,
  sample_review_consent boolean not null default false,
  status text not null default 'new' check (status in ('new', 'qualified', 'contacted', 'audit_in_progress', 'audit_ready', 'pilot_scheduled', 'converted', 'closed')),
  qualification_note text,
  audit_summary jsonb not null default '{}'::jsonb,
  source text not null default 'booka_website',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (cardinality(channels) > 0),
  check (consent_to_contact = true),
  check (vertical <> 'other' or nullif(trim(other_vertical), '') is not null)
);

create index if not exists idx_booka_revenue_requests_status_created
  on public.booka_revenue_requests (status, created_at desc);

create index if not exists idx_booka_revenue_requests_type_created
  on public.booka_revenue_requests (request_type, created_at desc);

create unique index if not exists idx_booka_revenue_requests_open_contact
  on public.booka_revenue_requests (request_type, lower(email))
  where status not in ('converted', 'closed');

alter table public.booka_revenue_requests enable row level security;
revoke all on public.booka_revenue_requests from anon, authenticated;
grant all on public.booka_revenue_requests to service_role;

drop policy if exists booka_revenue_requests_service_role on public.booka_revenue_requests;
create policy booka_revenue_requests_service_role
  on public.booka_revenue_requests for all to service_role
  using (true) with check (true);

-- Source: db/migrations/123_revenue_attribution_verification.sql
-- Migration 123: explicit revenue attribution and verification fields.
-- Legacy `value` remains untouched because it may represent a count, score, or lift.

alter table public.sias_outcome_attributions
  add column if not exists attribution_type text,
  add column if not exists verification_status text not null default 'unverified',
  add column if not exists amount_cents bigint,
  add column if not exists currency text,
  add column if not exists evidence_type text,
  add column if not exists verified_at timestamptz,
  add column if not exists verified_by uuid,
  add column if not exists attribution_window_started_at timestamptz;

alter table public.sias_outcome_attributions
  drop constraint if exists sias_outcome_attributions_type_check,
  drop constraint if exists sias_outcome_attributions_verification_check,
  drop constraint if exists sias_outcome_attributions_amount_check,
  drop constraint if exists sias_outcome_attributions_currency_check;

alter table public.sias_outcome_attributions
  add constraint sias_outcome_attributions_type_check
    check (
      attribution_type is null
      or attribution_type in ('processed', 'influenced', 'recovered')
    ),
  add constraint sias_outcome_attributions_verification_check
    check (
      verification_status in ('unverified', 'merchant_confirmed', 'system_verified', 'rejected')
    ),
  add constraint sias_outcome_attributions_amount_check
    check (amount_cents is null or amount_cents >= 0),
  add constraint sias_outcome_attributions_currency_check
    check (currency is null or currency ~ '^[A-Z]{3}$');

update public.sias_outcome_attributions
set attribution_type = case
  when signal = 'revenue_recovery' then 'recovered'
  when signal in ('upsell_conversion', 'repeat_booking_lift', 'reactivation_lift') then 'influenced'
  else null
end
where attribution_type is null;

create index if not exists idx_sias_attribution_tenant_type_verified
  on public.sias_outcome_attributions
  (tenant_id, attribution_type, verification_status, created_at desc);

-- Verification runs inside the transaction so any failure rolls back the release.

-- Source: scripts/sql/verify_booka_revenue_requests.sql
do $$
declare
  missing_columns text[];
begin
  select array_agg(required.name)
  into missing_columns
  from (values
    ('request_type'), ('business_name'), ('contact_name'), ('email'), ('phone'),
    ('vertical'), ('weekly_enquiry_band'), ('channels'), ('consent_to_contact'),
    ('sample_review_consent'), ('status'), ('audit_summary'), ('created_at'), ('updated_at')
  ) as required(name)
  where not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'booka_revenue_requests'
      and column_name = required.name
  );

  if missing_columns is not null then
    raise exception 'booka_revenue_requests missing columns: %', missing_columns;
  end if;

  if not exists (
    select 1
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public'
      and c.relname = 'booka_revenue_requests'
      and c.relrowsecurity
  ) then
    raise exception 'RLS is not enabled on booka_revenue_requests';
  end if;
end $$;

-- Source: scripts/sql/verify_revenue_attribution_verification.sql
do $$
declare
  missing_columns text[];
begin
  select array_agg(required.name order by required.name)
  into missing_columns
  from (values
    ('attribution_type'),
    ('verification_status'),
    ('amount_cents'),
    ('currency'),
    ('evidence_type'),
    ('verified_at'),
    ('verified_by'),
    ('attribution_window_started_at')
  ) as required(name)
  where not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'sias_outcome_attributions'
      and column_name = required.name
  );

  if missing_columns is not null then
    raise exception 'sias_outcome_attributions missing columns: %', missing_columns;
  end if;

  if exists (
    select 1
    from public.sias_outcome_attributions
    where amount_cents < 0
  ) then
    raise exception 'negative amount_cents found';
  end if;
end $$;

commit;

