/* eslint-disable @next/next/no-img-element -- tenant media hosts are runtime-configured. */
import { notFound } from 'next/navigation';
import type { Metadata } from 'next';
import { idFromPublicItemSlug, publicItemSlug } from '@/lib/storefront/config';
import { getPublicService } from '@/lib/storefront/public-storefront';
import { AskBookaButton, ConversionLink, StickyConversionBar } from '@/components/storefront/StorefrontConversion';
import StorefrontPageView from '@/components/storefront/StorefrontPageView';
type Props = { params: Promise<{ slug: string; serviceSlug: string }> }; export const dynamic = 'force-dynamic';
const formatMoney = (cents: number, currency: string) => new Intl.NumberFormat('en-NG', { style: 'currency', currency, maximumFractionDigits: 0 }).format(cents / 100);
async function load(params: Props['params']) { const { slug, serviceSlug } = await params; const id = idFromPublicItemSlug(serviceSlug); return id ? getPublicService(slug, id) : null; }
export async function generateMetadata({ params }: Props): Promise<Metadata> { const result = await load(params); return result ? { title: `${result.service.name} | ${result.storefront.tenant.name}`, description: result.service.description || `Book ${result.service.name} with ${result.storefront.tenant.name}`, alternates: { canonical: `/${result.storefront.tenant.slug}/services/${publicItemSlug(result.service.name, result.service.id)}` } } : {}; }
export default async function ServicePage({ params }: Props) {
  const result = await load(params); if (!result) notFound(); const { storefront, service } = result;
  const price = formatMoney(service.price_cents, storefront.currency); const staff = storefront.staff.filter((person) => person.services.includes(service.id)); const booking = `/book/${storefront.tenant.slug}?service=${service.id}`;
  const jsonLd = { '@context': 'https://schema.org', '@type': 'Service', name: service.name, description: service.description || undefined, provider: { '@type': 'LocalBusiness', name: storefront.tenant.name }, offers: { '@type': 'Offer', price: service.price_cents / 100, priceCurrency: storefront.currency } };
  return <main className="min-h-screen bg-[#fbfcf9] pb-24"><StorefrontPageView slug={storefront.tenant.slug} tenantId={storefront.tenant.id} pageType="service" serviceId={service.id} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><header className="border-b border-[#dbe5dc] bg-white"><div className="mx-auto max-w-5xl px-5 py-4"><a href={`/${storefront.tenant.slug}`} className="text-sm font-bold text-[#254b37]">← {storefront.tenant.name}</a></div></header><article className="mx-auto max-w-5xl px-5 py-10 sm:px-8"><div className="grid gap-9 lg:grid-cols-[1.1fr_.9fr]"><div>{service.image_url ? <img src={service.image_url} alt={service.name} className="aspect-[4/3] w-full rounded-[2rem] object-cover" /> : <div className="aspect-[4/3] rounded-[2rem] bg-[radial-gradient(circle_at_20%_20%,#d6e7c5,transparent_32%),#eaf2e9]" />}</div><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#39704e]">{service.category || 'Service'}</p><h1 className="mt-3 font-[family-name:var(--font-booka-display-loaded)] text-5xl leading-none text-[#12261c]">{service.name}</h1><p className="mt-5 text-lg leading-8 text-[#526356]">{service.description || 'A tailored experience, with clear details before you book.'}</p><div className="mt-7 flex items-center gap-4"><strong className="text-2xl text-[#173423]">{price}</strong><span className="text-sm text-[#657568]">{service.duration_minutes} minutes</span></div><div className="mt-8 flex flex-wrap gap-3"><ConversionLink slug={storefront.tenant.slug} tenantId={storefront.tenant.id} label="Book now" href={booking} pageType="service" serviceId={service.id} priceLabel={price} /><AskBookaButton slug={storefront.tenant.slug} tenantId={storefront.tenant.id} pageType="service" serviceId={service.id} /></div></div></div>{staff.length > 0 && <section className="mt-14"><h2 className="font-[family-name:var(--font-booka-display-loaded)] text-3xl text-[#12261c]">Available with</h2><div className="mt-5 flex flex-wrap gap-3">{staff.map((person) => <div key={person.id} className="rounded-2xl border border-[#dbe5dc] bg-white px-5 py-4 font-bold text-[#193426]">{person.name}</div>)}</div></section>}{storefront.faqs.length > 0 && <section className="mt-14"><h2 className="font-[family-name:var(--font-booka-display-loaded)] text-3xl text-[#12261c]">Before you book</h2><div className="mt-5 divide-y divide-[#dbe5dc] rounded-2xl border border-[#dbe5dc] bg-white px-5">{storefront.faqs.slice(0, 5).map((faq) => <details key={faq.id} className="py-4"><summary className="cursor-pointer font-bold">{faq.question}</summary><p className="mt-3 text-sm text-[#526356]">{faq.answer}</p></details>)}</div></section>}</article><StickyConversionBar slug={storefront.tenant.slug} tenantId={storefront.tenant.id} label="Book now" href={booking} pageType="service" serviceId={service.id} priceLabel={price} /></main>;
}
