import Link from 'next/link';
import { CTASection } from '@/components/capability/conversion/CTASection';
import { Card } from '@/components/capability/core/Card';
import { Container } from '@/components/capability/core/Container';
import { Heading } from '@/components/capability/core/Heading';
import { Section } from '@/components/capability/core/Section';
import { Text } from '@/components/capability/core/Text';
const areas = [['Corporate advisory', 'Governance, entity matters, commercial arrangements, and practical legal-operating questions.'], ['Mergers & acquisitions', 'A structured starting point for transaction planning, diligence, and documentation conversations.'], ['Employment', 'Information about workplace policies, executive arrangements, and employment-related processes.'], ['Technology & data', 'A starting point for technology agreements, data practices, and digital-business questions.'], ['Real estate', 'Commercial property and project-related information presented for an initial discussion.'], ['Dispute resolution', 'Pathways for understanding disputes, negotiation, and formal resolution options.']];
export const metadata = { title: 'Practice areas — Meridian Legal', description: 'Illustrative corporate-law practice information for the Meridian Legal capability demonstrator.' };
export default function PracticeAreasPage() { return <main><Section><Container width="wide"><p className="text-xs font-semibold uppercase tracking-[.18em]" style={{ color: 'var(--sc-primary)' }}>Practice areas</p><Heading level={1} className="mt-3">Find the right starting point.</Heading><Text size="lg" tone="muted" className="mt-4 max-w-2xl">These are illustrative descriptions of how a firm can organise its expertise. They are general information, not legal advice.</Text><div className="mt-10 grid gap-px border border-current/10 bg-current/10 md:grid-cols-2 lg:grid-cols-3">{areas.map(([title, copy]) => <Card key={title} className="rounded-none border-0"><Heading level={2} className="text-xl">{title}</Heading><Text tone="muted" className="mt-3">{copy}</Text><Link className="mt-5 inline-block text-sm font-medium underline underline-offset-4" href="/showcase/demos/meridian-legal/contact">Discuss this area →</Link></Card>)}</div></Container></Section><CTASection title="Need a conversation, not a conclusion?" subtitle="The local inquiry form makes clear that a conflict check and engagement would happen separately in a real firm workflow." cta={{ label: 'Request a consultation', href: '/showcase/demos/meridian-legal/contact' }} /></main>; }
