import Link from 'next/link';
import { CTASection } from '@/components/capability/conversion/CTASection';
import { Card } from '@/components/capability/core/Card';
import { Container } from '@/components/capability/core/Container';
import { Heading } from '@/components/capability/core/Heading';
import { Section } from '@/components/capability/core/Section';
import { Text } from '@/components/capability/core/Text';
const services = [['Build & fit-out', 'A practical service pattern for new-build and interior fit-out conversations.'], ['Renovation', 'A clear entry point for phased renovation and upgrade planning.'], ['Project coordination', 'A project-communication pattern designed for cross-trade coordination.']];
export const metadata = { title: 'Forge Build — Construction capability', description: 'A fictional construction capability demonstrator by TechClave.' };
export default function ForgeHome() { return <main><section className="border-b border-current/10"><Container width="wide" className="py-20 lg:py-28"><p className="text-xs font-semibold uppercase tracking-[.2em]" style={{ color: 'var(--sc-primary)' }}>Capability Demonstrator · Construction</p><Heading level={1} className="mt-5 max-w-4xl">Built for the work between a brief and a better site.</Heading><Text size="lg" tone="muted" className="mt-6 max-w-2xl">Forge Build is a fictional contractor experience designed to put capability, process, and the first quote conversation on a clear foundation.</Text><div className="mt-9 flex flex-wrap gap-4"><Link className="sc-primary px-6 py-3 text-sm font-bold" href="/showcase/demos/forge-build/contact">Request a quote</Link><Link className="border border-current/20 px-6 py-3 text-sm font-bold" href="/showcase/demos/forge-build/projects">View illustrative projects</Link></div><div className="mt-14 grid border border-current/15 md:grid-cols-3">{['Scope clearly', 'Plan deliberately', 'Build responsibly'].map((item, i) => <p key={item} className="border-current/15 p-5 text-sm font-semibold md:border-r last:md:border-r-0"><span className="mr-3 opacity-60">0{i + 1}</span>{item}</p>)}</div></Container></section><Section tone="surface"><Container width="wide"><p className="text-xs uppercase tracking-[.18em] sc-eyebrow-muted">Capabilities</p><Heading level={2} className="mt-3">A project site that works as hard as the team behind it.</Heading><div className="mt-8 grid gap-px border border-current/10 bg-current/10 md:grid-cols-3">{services.map(([title, copy]) => <Card key={title} className="rounded-none border-0"><Heading level={3} className="text-xl">{title}</Heading><Text tone="muted" className="mt-3">{copy}</Text></Card>)}</div></Container></Section><CTASection title="Bring the broad outline." subtitle="The local quote-request pattern shows how a contractor can collect the first practical details without sending data anywhere." cta={{ label: 'Request a quote', href: '/showcase/demos/forge-build/contact' }} /></main>; }
