import Link from 'next/link';
import { CTASection } from '@/components/capability/conversion/CTASection';
import { Card } from '@/components/capability/core/Card';
import { Container } from '@/components/capability/core/Container';
import { Heading } from '@/components/capability/core/Heading';
import { Section } from '@/components/capability/core/Section';
import { Text } from '@/components/capability/core/Text';
const areas = [['Corporate & commercial', 'Structure, governance, and day-to-day commercial questions.'], ['Transactions', 'A clear starting point for acquisitions, investments, and reorganisations.'], ['Dispute resolution', 'Information about formal and negotiated resolution pathways.']];
export const metadata = { title: 'Meridian Legal — Corporate counsel information', description: 'A fictional corporate-law capability demonstrator by TechClave.' };
export default function MeridianHome() { return <main><section className="border-b border-current/10"><Container width="wide" className="py-20 lg:py-28"><p className="text-xs font-semibold uppercase tracking-[.2em]" style={{ color: 'var(--sc-primary)' }}>Capability Demonstrator · Corporate law</p><div className="mt-6 grid gap-12 lg:grid-cols-[1.2fr_.8fr]"><div><Heading level={1} className="max-w-3xl">Measured counsel for decisions that deserve care.</Heading><Text size="lg" tone="muted" className="mt-6 max-w-2xl">Meridian Legal is a fictional firm experience designed to make legal capabilities, the people behind them, and the first contact process clear without turning information into advice.</Text><div className="mt-9 flex flex-wrap gap-4"><Link className="sc-primary px-6 py-3 text-sm font-medium" href="/showcase/demos/meridian-legal/contact">Request a consultation</Link><Link className="border border-current/20 px-6 py-3 text-sm font-medium" href="/showcase/demos/meridian-legal/practice-areas">Explore practice areas</Link></div></div><aside className="border-l-2 pl-6" style={{ borderColor: 'var(--sc-accent)' }}><p className="text-sm font-semibold">Important notice</p><Text tone="muted" className="mt-3 text-sm">Information on this fictional demonstrator is not legal advice. Viewing it or sending the local mock form does not form an attorney-client relationship or complete a conflict check.</Text></aside></div></Container></section><Section tone="surface"><Container width="wide"><p className="text-xs uppercase tracking-[.18em] opacity-60">Areas of focus</p><Heading level={2} className="mt-3">Built around the questions clients bring first.</Heading><div className="mt-8 grid gap-px border border-current/10 bg-current/10 md:grid-cols-3">{areas.map(([title, copy]) => <Card key={title} className="rounded-none border-0"><Heading level={3} className="text-xl">{title}</Heading><Text tone="muted" className="mt-3">{copy}</Text></Card>)}</div></Container></Section><Section><Container width="wide" className="grid gap-10 lg:grid-cols-2"><div><p className="text-xs uppercase tracking-[.18em] opacity-60">The Meridian approach</p><Heading level={2} className="mt-3">Authority begins with being precise about what a website can do.</Heading></div><div className="space-y-5 border-l border-current/15 pl-6"><Text tone="muted">A useful firm site helps visitors recognise the relevant area of focus, understand who they may speak with, and approach contact with the right expectations.</Text><Link className="text-sm font-medium underline underline-offset-4" href="/showcase/demos/meridian-legal/team">Meet the illustrative team →</Link></div></Container></Section><CTASection title="Start with a considered inquiry." subtitle="Review the local consultation flow and the notices that make its limits explicit." cta={{ label: 'Request a consultation', href: '/showcase/demos/meridian-legal/contact' }} /></main>; }
