import { z } from 'zod';
import { createHttpHandler, parseJsonBody } from '@/lib/error-handling/route-handler';
import { ApiErrorFactory } from '@/lib/error-handling/api-error';

const CampaignSchema = z.object({ title: z.string().trim().min(1).max(160), copy: z.string().trim().max(1000).optional(), cta_label: z.string().trim().max(60).optional(), target_type: z.enum(['service', 'product', 'storefront']).optional(), target_ids: z.array(z.string().uuid()).max(30).optional(), start_at: z.string().datetime().optional(), end_at: z.string().datetime().optional(), status: z.enum(['draft', 'active', 'paused']).optional() }).superRefine((value, issue) => { if (value.start_at && value.end_at && new Date(value.end_at) <= new Date(value.start_at)) issue.addIssue({ code: 'custom', message: 'end_at must be after start_at' }); });

function requireTenant(ctx: { params?: Record<string, unknown>; user?: { tenantId?: string; role?: string } | null }) { const tenantId = ctx.params?.tenantId; if (!tenantId || typeof tenantId !== 'string') throw ApiErrorFactory.badRequest('Tenant ID required'); if (ctx.user?.role !== 'superadmin' && ctx.user?.tenantId !== tenantId) throw ApiErrorFactory.forbidden('Access to this tenant is not allowed'); return tenantId; }
export const GET = createHttpHandler(async (ctx) => { const tenantId = requireTenant(ctx); const { data, error } = await ctx.supabase.from('storefront_campaigns').select('id,status,title,copy,cta_label,target_type,target_ids,start_at,end_at,source,approval_metadata,created_at,updated_at').eq('tenant_id', tenantId).order('created_at', { ascending: false }); if (error) throw ApiErrorFactory.databaseError(error); return data ?? []; }, 'GET', { auth: true, roles: ['owner', 'manager', 'superadmin'] });
export const POST = createHttpHandler(async (ctx) => { const tenantId = requireTenant(ctx); const parsed = CampaignSchema.safeParse(await parseJsonBody(ctx.request)); if (!parsed.success) throw ApiErrorFactory.validationError({ campaign: parsed.error.issues[0]?.message ?? 'Invalid campaign' }); const status = parsed.data.status ?? 'draft'; const { data, error } = await ctx.supabase.from('storefront_campaigns').insert({ tenant_id: tenantId, ...parsed.data, status, source: 'owner', approval_metadata: status === 'active' ? { approved_by: ctx.user!.id, approved_at: new Date().toISOString() } : {} }).select('id,status,title,start_at,end_at').single(); if (error) throw ApiErrorFactory.databaseError(error); return data; }, 'POST', { auth: true, roles: ['owner', 'manager', 'superadmin'] });
