import { FAQ } from '@/components/capability/conversion/FAQ';
import { Card } from '@/components/capability/core/Card';
import { Container } from '@/components/capability/core/Container';
import { Heading } from '@/components/capability/core/Heading';
import { Section } from '@/components/capability/core/Section';
import { Text } from '@/components/capability/core/Text';

export const metadata = { title: 'Patient information — Northstar Clinic', description: 'Illustrative patient information for the Northstar Clinic capability demonstrator.' };

export default function PatientInformationPage() {
  return <main><Section><Container width="wide"><p className="text-xs font-semibold uppercase tracking-[.18em]" style={{ color: 'var(--sc-eyebrow)' }}>Patient information</p><Heading level={1} className="mt-3">Practical details should not be hard to find.</Heading><Text size="lg" tone="muted" className="mt-4 max-w-2xl">A calm information layer can make an appointment request feel more informed. The details below are illustrative and do not describe a real clinic.</Text><div className="mt-10 grid gap-5 md:grid-cols-3"><Card><Heading level={2} className="text-xl">Before your visit</Heading><Text tone="muted" className="mt-3">Bring relevant identification and any information a real clinic asks you to prepare. Specific requirements should always be confirmed with the clinic directly.</Text></Card><Card><Heading level={2} className="text-xl">Payment and insurance</Heading><Text tone="muted" className="mt-3">A production clinic site can explain accepted payment methods and how patients should confirm insurance coverage before an appointment.</Text></Card><Card><Heading level={2} className="text-xl">Privacy</Heading><Text tone="muted" className="mt-3">A live clinic must provide its own privacy notice and handling process. This demonstrator does not collect or transmit form data.</Text></Card></div></Container></Section><Section tone="surface"><FAQ title="Helpful questions" items={[{ question: 'Is Northstar a real medical clinic?', answer: 'No. It is a fictional TechClave capability demonstrator created to show a private healthcare website and appointment-request flow.' }, { question: 'Can I get medical advice here?', answer: 'No. This site provides no medical advice, diagnosis, or treatment. Contact a qualified clinician for medical concerns.' }, { question: 'What if I need urgent help?', answer: 'For emergencies, contact your local emergency services. Do not use this demonstrator as an emergency contact point.' }]} /></Section></main>;
}
