import { LeadForm } from '@/components/capability/forms/LeadForm';
import { Card } from '@/components/capability/core/Card';
import { Container } from '@/components/capability/core/Container';
import { Heading } from '@/components/capability/core/Heading';
import { Section } from '@/components/capability/core/Section';
import { Text } from '@/components/capability/core/Text';
const fields = [{ name: 'name', label: 'Your name', required: true, placeholder: 'Name' }, { name: 'email', label: 'Email address', type: 'email' as const, required: true, placeholder: 'you@example.com' }, { name: 'location', label: 'Project location', required: true, placeholder: 'City or area' }, { name: 'brief', label: 'Project outline', type: 'textarea' as const, required: true, placeholder: 'Tell us the broad scope, timing, and any key constraints.' }];
export const metadata = { title: 'Request a quote — Forge Build', description: 'A local-only quote request form in the Forge Build capability demonstrator.' };
export default function ContactPage() { return <main><Section><Container width="wide" className="grid gap-10 lg:grid-cols-[.85fr_1.15fr]"><div><p className="text-xs font-semibold uppercase tracking-[.18em]" style={{ color: 'var(--sc-primary)' }}>Quote request</p><Heading level={1} className="mt-3">Start with the broad outline.</Heading><Text size="lg" tone="muted" className="mt-4">This local-only form demonstrates an early project inquiry pattern. It does not send, store, price, or assess any submitted information.</Text><Card className="mt-8 rounded-none"><Heading level={2} className="text-xl">Service area</Heading><Text tone="muted" className="mt-3">A live contractor site can use this space for verified operating areas, site-visit policy, and response expectations. Forge Build is fictional.</Text></Card></div><Card className="rounded-none p-6 sm:p-8"><Heading level={2} className="text-2xl">Project context</Heading><Text tone="muted" className="mt-2">The form deliberately asks for enough context to begin a useful conversation—without pretending a quote has been produced.</Text><div className="mt-7"><LeadForm fields={fields} submitLabel="Send quote request" /></div></Card></Container></Section></main>; }
