import { CTASection } from '@/components/capability/conversion/CTASection';
import { FAQ } from '@/components/capability/conversion/FAQ';
import { Card } from '@/components/capability/core/Card';
import { Container } from '@/components/capability/core/Container';
import { Heading } from '@/components/capability/core/Heading';
import { Section } from '@/components/capability/core/Section';
import { Text } from '@/components/capability/core/Text';

export const metadata = { title: 'Solar solutions', description: 'Residential and commercial solar planning paths in the SunGrid capability demonstrator.' };

export default function SolutionsPage() { return <main><Section><Container width="wide"><p className="text-xs font-semibold uppercase tracking-[0.2em]" style={{ color: 'var(--sc-accent)' }}>Solutions</p><Heading level={1} className="mt-4 max-w-3xl">A solar system is a set of decisions, not a box of panels.</Heading><Text size="lg" tone="muted" className="mt-5 max-w-2xl">This demonstrator shows two discovery paths that make those decisions easier to understand before a site visit.</Text></Container></Section><Section tone="surface"><Container width="wide" className="grid gap-6 lg:grid-cols-2"><Solution id="residential" number="01" title="Residential continuity" copy="Prioritise the appliances and hours that matter most. An assessment can then establish suitable panel, battery, inverter, and protection choices for your actual home." bullets={['Load inventory and usage pattern', 'Roof, shade, and cable-route review', 'Critical-circuit and battery-backup priorities']} /><Solution id="commercial" number="02" title="Commercial resilience" copy="Start from the operating profile: production equipment, refrigeration, IT, lighting, and the cost of interruption. The design brief follows the business—not a generic package." bullets={['Peak-demand and operating-hour mapping', 'Phased expansion considerations', 'Site safety, monitoring, and handover requirements']} /></Container></Section><Section><FAQ title="Useful questions before an assessment" items={[{ question: 'Can solar eliminate every utility bill?', answer: 'Not necessarily. Actual offset depends on demand timing, system size, storage, shading, tariff structure, and the final site design.' }, { question: 'Do I need batteries?', answer: 'That depends on which loads must stay available outside solar-generation hours. An assessment should separate essential loads from nice-to-have loads.' }, { question: 'Can a system expand later?', answer: 'Sometimes. Expansion should be considered during initial design because inverter, battery, roof, and cable decisions can affect future options.' }]} /></Section><CTASection title="Turn your energy questions into an assessment brief." cta={{ label: 'Request assessment', href: '/showcase/demos/sungrid-energy/contact' }} /></main>; }
function Solution({ id, number, title, copy, bullets }: { id: string; number: string; title: string; copy: string; bullets: string[] }) { return <Card><p className="sc-display text-4xl" style={{ color: 'var(--sc-primary)' }}>{number}</p><Heading id={id} level={2} className="mt-5">{title}</Heading><Text tone="muted" className="mt-4">{copy}</Text><ul className="mt-6 space-y-3 text-sm">{bullets.map((bullet) => <li key={bullet} className="border-l border-current/20 pl-3">{bullet}</li>)}</ul></Card>; }
