/* eslint-disable @next/next/no-img-element -- tenant media hosts are runtime-configured. */
import type { PublicStorefront, StorefrontService } from '@/lib/storefront/public-storefront';
import { publicItemSlug, type StorefrontBlock } from '@/lib/storefront/config';
import { AskBookaButton, ConversionLink, StickyConversionBar } from './StorefrontConversion';
import { primaryActionForCommercialMotion } from '@/lib/business-model';

function money(amount: number, currency: string) { try { return new Intl.NumberFormat('en-NG', { style: 'currency', currency, maximumFractionDigits: 0 }).format(amount / 100); } catch { return `${currency} ${amount / 100}`; } }
function serviceHref(storefront: PublicStorefront, service: StorefrontService) { return `/${storefront.tenant.slug}/services/${publicItemSlug(service.name, service.id)}`; }

function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="mx-auto max-w-6xl px-5 py-12 sm:px-8"><h2 className="font-[family-name:var(--font-booka-display-loaded)] text-3xl font-semibold tracking-tight text-[#12261c]">{title}</h2><div className="mt-6">{children}</div></section>; }

function Services({ storefront, block }: { storefront: PublicStorefront; block: StorefrontBlock }) {
  const services = storefront.services.slice(0, block.limit ?? 8);
  if (!services.length) return null;
  return <Section title={block.heading ?? (block.id === 'featured_services' ? 'Most booked' : 'Explore our services')}><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{services.map((service) => <a key={service.id} href={serviceHref(storefront, service)} className="group overflow-hidden rounded-[1.5rem] border border-[#dbe5dc] bg-white p-4 transition hover:-translate-y-1 hover:shadow-xl"><div className="aspect-[16/10] overflow-hidden rounded-2xl bg-[#eaf1e9]">{service.image_url ? <img src={service.image_url} alt="" className="h-full w-full object-cover transition duration-500 group-hover:scale-105" /> : <div className="h-full bg-[radial-gradient(circle_at_80%_15%,#cfdfce,transparent_35%),linear-gradient(130deg,#e8f0e7,#f7faf6)]" />}</div><div className="mt-4 flex items-start justify-between gap-3"><div><h3 className="font-bold text-[#12261c]">{service.name}</h3><p className="mt-1 line-clamp-2 text-sm text-[#5b6c60]">{service.description || 'A tailored experience, booked around your schedule.'}</p></div><span className="whitespace-nowrap text-sm font-bold text-[#205c3e]">{money(service.price_cents, storefront.currency)}</span></div><p className="mt-3 text-xs font-semibold uppercase tracking-[.12em] text-[#718176]">{service.duration_minutes} min · Book details</p></a>)}</div></Section>;
}

export default function StorefrontPage({ storefront }: { storefront: PublicStorefront }) {
  const { tenant } = storefront;
  const bookingHref = `/book/${tenant.slug}`;
  const defaultAction = primaryActionForCommercialMotion(storefront.commercialMotion);
  const primary = storefront.config.primaryCta || defaultAction.label;
  const primaryHref = defaultAction.kind === 'shop' ? `/store/${tenant.slug}` : bookingHref;
  const blocks: Record<string, (block: StorefrontBlock) => React.ReactNode> = {
    hero: () => <section className="overflow-hidden bg-[#eaf2e9]"><div className="mx-auto grid max-w-6xl gap-9 px-5 py-16 sm:px-8 lg:grid-cols-[1.2fr_.8fr] lg:py-24"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#39704e]">{tenant.industry || 'Booka business'}</p><h1 className="mt-4 max-w-3xl font-[family-name:var(--font-booka-display-loaded)] text-5xl font-semibold leading-[.98] tracking-tight text-[#12261c] sm:text-6xl">{tenant.name}</h1><p className="mt-5 max-w-xl text-lg leading-8 text-[#425646]">{tenant.description || 'A front desk that is always ready to help customers book, buy, or get the right answer.'}</p><div className="mt-8 flex flex-wrap gap-3">{defaultAction.kind === 'ask' ? <AskBookaButton slug={tenant.slug} tenantId={tenant.id} pageType="storefront" /> : <ConversionLink slug={tenant.slug} tenantId={tenant.id} label={primary} href={primaryHref} pageType="storefront" />} {defaultAction.kind !== 'ask' && <AskBookaButton slug={tenant.slug} tenantId={tenant.id} pageType="storefront" />}</div></div><div className="relative min-h-60 overflow-hidden rounded-[2rem] bg-[#264d38] shadow-2xl"><div className="absolute inset-0 bg-[radial-gradient(circle_at_20%_20%,rgba(213,235,185,.72),transparent_25%),radial-gradient(circle_at_80%_75%,rgba(241,198,122,.8),transparent_30%)]" />{tenant.logo && <img src={tenant.logo} alt="" className="absolute inset-0 h-full w-full object-cover opacity-80 mix-blend-luminosity" />}<p className="absolute bottom-7 left-7 max-w-48 font-[family-name:var(--font-booka-display-loaded)] text-2xl text-white">Made for the moment you need us.</p></div></div></section>,
    business_intro: () => tenant.description ? <Section title="A little about us"><p className="max-w-3xl text-lg leading-8 text-[#526356]">{tenant.description}</p></Section> : null,
    featured_services: (b) => <Services storefront={storefront} block={b} />, service_grid: (b) => <Services storefront={storefront} block={b} />,
    service_categories: () => storefront.services.length ? <Section title="Find what you need"><div className="flex flex-wrap gap-2">{Array.from(new Set(storefront.services.map((s) => s.category).filter(Boolean))).map((category) => <span key={category} className="rounded-full bg-[#eaf2e9] px-4 py-2 text-sm font-bold text-[#254b37]">{category}</span>)}</div></Section> : null,
    product_grid: (b) => storefront.products.length ? <Section title={b.heading ?? 'Shop products'}><div className="grid grid-cols-2 gap-4 lg:grid-cols-4">{storefront.products.slice(0, b.limit ?? 8).map((product) => <a href={`/${tenant.slug}/products/${publicItemSlug(product.name, product.id)}`} key={product.id} className="rounded-2xl border border-[#dbe5dc] bg-white p-3 transition hover:shadow-lg"><div className="aspect-square overflow-hidden rounded-xl bg-[#edf3ec]">{product.image && <img src={product.image} alt="" className="h-full w-full object-cover" />}</div><h3 className="mt-3 line-clamp-2 font-bold text-[#12261c]">{product.name}</h3><p className="mt-1 text-sm font-bold text-[#205c3e]">{money(product.price_cents, storefront.currency)}</p></a>)}</div></Section> : null,
    promotion: () => storefront.campaign ? <section className="mx-auto max-w-6xl px-5 py-6 sm:px-8"><div className="rounded-[1.5rem] bg-[#254b37] p-7 text-white"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#d8eabf]">Limited-time offer</p><h2 className="mt-2 font-[family-name:var(--font-booka-display-loaded)] text-3xl">{storefront.campaign.title}</h2>{storefront.campaign.copy && <p className="mt-2 max-w-2xl text-[#e6f0e6]">{storefront.campaign.copy}</p>}</div></section> : null,
    gallery: () => storefront.services.some((s) => s.image_url) ? <Section title="In the details"><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{storefront.services.filter((s) => s.image_url).slice(0, 4).map((service) => <img key={service.id} src={service.image_url!} alt={`${service.name} at ${tenant.name}`} className="aspect-square rounded-2xl object-cover" />)}</div></Section> : null,
    staff: () => storefront.staff.length ? <Section title="Meet the team"><div className="flex flex-wrap gap-3">{storefront.staff.map((person) => <div key={person.id} className="rounded-2xl border border-[#dbe5dc] bg-white px-5 py-4"><p className="font-bold text-[#12261c]">{person.name}</p><p className="mt-1 text-xs text-[#6b7a6e]">Available to book</p></div>)}</div></Section> : null,
    reviews: () => storefront.reviews.length ? <Section title="Loved by customers"><div className="grid gap-4 md:grid-cols-3">{storefront.reviews.slice(0, 6).map((review) => <figure key={review.id} className="rounded-2xl bg-[#f4f8f3] p-5"><div className="text-[#d28330]">{'★'.repeat(Math.round(review.rating))}</div>{review.comment && <blockquote className="mt-3 text-sm leading-6 text-[#344737]">“{review.comment}”</blockquote>}<figcaption className="mt-4 text-xs font-bold uppercase tracking-wide text-[#657568]">{review.customer_name}</figcaption></figure>)}</div></Section> : null,
    benefits: () => <Section title="Why choose us"><div className="grid gap-4 sm:grid-cols-3">{['Clear pricing', 'Thoughtful service', 'Easy booking'].map((item) => <div key={item} className="rounded-2xl border border-[#dbe5dc] bg-white p-5 font-bold text-[#193426]">{item}</div>)}</div></Section>,
    packages: () => null,
    faq: () => storefront.faqs.length ? <Section title="Questions, answered"><div className="divide-y divide-[#dbe5dc] rounded-2xl border border-[#dbe5dc] bg-white px-5">{storefront.faqs.map((faq) => <details key={faq.id} className="py-4"><summary className="cursor-pointer font-bold text-[#193426]">{faq.question}</summary><p className="mt-3 max-w-3xl text-sm leading-6 text-[#5b6c60]">{faq.answer}</p></details>)}</div></Section> : null,
    business_hours: () => <Section title="Plan your visit"><p className="text-[#5b6c60]">Check availability in the booking flow for the latest open slots.</p></Section>,
    location: () => (tenant.address || tenant.phone) ? <Section title="Find us"><div className="rounded-2xl bg-[#f4f8f3] p-6 text-[#405443]">{tenant.address && <p>{tenant.address}</p>}{tenant.phone && <a href={`tel:${tenant.phone}`} className="mt-2 inline-block font-bold underline">{tenant.phone}</a>}</div></Section> : null,
    ai_front_desk_cta: () => <section className="bg-[#12261c] px-5 py-14 text-center text-white"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#d7e9ba]">The Booka AI Front Desk</p><h2 className="mx-auto mt-3 max-w-2xl font-[family-name:var(--font-booka-display-loaded)] text-3xl">Not sure what to book? Ask us anything.</h2><div className="mt-6"><AskBookaButton slug={tenant.slug} tenantId={tenant.id} pageType="storefront" /></div></section>,
    final_cta: () => <section className="px-5 py-16 text-center"><h2 className="font-[family-name:var(--font-booka-display-loaded)] text-4xl text-[#12261c]">Ready when you are.</h2><div className="mt-6">{defaultAction.kind === 'ask' ? <AskBookaButton slug={tenant.slug} tenantId={tenant.id} pageType="storefront" /> : <ConversionLink slug={tenant.slug} tenantId={tenant.id} label={primary} href={primaryHref} pageType="storefront" />}</div></section>,
    related_services: () => null, related_products: () => null,
  };
  return <main className="min-h-screen bg-[#fbfcf9] pb-20"><header className="sticky top-0 z-30 border-b border-[#dbe5dc] bg-[#fbfcf9]/90 backdrop-blur"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-3 sm:px-8"><a href={`/${tenant.slug}`} className="flex items-center gap-3 font-bold text-[#12261c]">{tenant.logo ? <img src={tenant.logo} alt="" className="h-8 w-8 rounded-full object-cover" /> : <span className="flex h-8 w-8 items-center justify-center rounded-full bg-[#254b37] text-white">{tenant.name.charAt(0)}</span>}{tenant.name}</a>{defaultAction.kind === 'ask' ? <AskBookaButton slug={tenant.slug} tenantId={tenant.id} pageType="storefront" /> : <a href={primaryHref} className="text-sm font-bold text-[#254b37]">{primary}</a>}</div></header>{storefront.config.blocks.filter((block) => block.visible !== false).map((block, index) => <div key={`${block.id}-${index}`}>{blocks[block.id]?.(block)}</div>)}{defaultAction.kind !== 'ask' && <StickyConversionBar slug={tenant.slug} tenantId={tenant.id} label={primary} href={primaryHref} pageType="storefront" />}</main>;
}
