import Link from 'next/link';
import { Card } from '@/components/capability/core/Card';
import { Container } from '@/components/capability/core/Container';
import { Heading } from '@/components/capability/core/Heading';
import { Section } from '@/components/capability/core/Section';
import { Text } from '@/components/capability/core/Text';
const services = [['Pre-construction', 'Discovery, scope framing, and planning patterns for a more useful project conversation.'], ['Commercial build', 'An illustrative pattern for retail, workplace, and operational-space build work.'], ['Residential renovation', 'A clear information path for homeowners comparing renovation approaches.'], ['Interiors & fit-out', 'A service structure for workplace and customer-facing interiors.'], ['Repairs & upgrades', 'Practical context for repair, upgrade, and maintenance work.'], ['Project coordination', 'A process layer that clarifies stakeholders, sequence, and decisions.']];
export const metadata = { title: 'Services — Forge Build', description: 'Illustrative construction services for the Forge Build capability demonstrator.' };
export default function ServicesPage() { return <main><Section><Container width="wide"><p className="text-xs font-semibold uppercase tracking-[.18em]" style={{ color: 'var(--sc-primary)' }}>Services</p><Heading level={1} className="mt-3">From the first measure to the final handover.</Heading><Text size="lg" tone="muted" className="mt-4 max-w-2xl">This fictional directory demonstrates how a contractor can make scope visible before a quote conversation. It does not describe live services or availability.</Text><div className="mt-10 grid gap-px border border-current/10 bg-current/10 md:grid-cols-2 lg:grid-cols-3">{services.map(([title, copy]) => <Card key={title} className="rounded-none border-0"><Heading level={2} className="text-xl">{title}</Heading><Text tone="muted" className="mt-3">{copy}</Text><Link className="mt-5 inline-block text-sm font-bold underline underline-offset-4" href="/showcase/demos/forge-build/contact">Discuss your project →</Link></Card>)}</div></Container></Section></main>; }
