import { z } from 'zod';
import { createHttpHandler, parseJsonBody } from '@/lib/error-handling/route-handler';
import { ApiErrorFactory } from '@/lib/error-handling/api-error';
import { createSupabaseAdminClient } from '@/lib/supabase/server';
import { getTenantPublicInfo } from '@/lib/publicBookingService';
import { createStorefrontContextToken } from '@/lib/storefront/context';

const ContextSchema = z.object({ page_type: z.enum(['storefront', 'service', 'product', 'campaign']), service_id: z.string().uuid().optional(), product_id: z.string().uuid().optional(), campaign_id: z.string().uuid().optional(), session_id: z.string().uuid().optional(), referrer: z.string().max(2048).optional() });
export const POST = createHttpHandler(async (ctx) => { const slug = ctx.params?.slug; if (!slug || typeof slug !== 'string') throw ApiErrorFactory.badRequest('Slug required'); const parsed = ContextSchema.safeParse(await parseJsonBody(ctx.request)); if (!parsed.success) throw ApiErrorFactory.validationError({ context: 'Invalid storefront context' }); const tenant = await getTenantPublicInfo(slug); const admin = createSupabaseAdminClient(); const { data: row } = await admin.from('tenants').select('routing_code, lifecycle_state').eq('id', tenant.id).maybeSingle(); if (!row || (row.lifecycle_state && row.lifecycle_state !== 'active')) throw ApiErrorFactory.notFound('Tenant'); const token = createStorefrontContextToken({ tenantId: tenant.id, pageType: parsed.data.page_type, serviceId: parsed.data.service_id, productId: parsed.data.product_id, campaignId: parsed.data.campaign_id, referrer: parsed.data.referrer }); await admin.from('storefront_events').insert({ tenant_id: tenant.id, event_type: 'ask_booka_opened', page_type: parsed.data.page_type, session_id: parsed.data.session_id ?? null, service_id: parsed.data.service_id ?? null, product_id: parsed.data.product_id ?? null, campaign_id: parsed.data.campaign_id ?? null, referrer: parsed.data.referrer ?? null, metadata: {} }).then(() => undefined).catch(() => undefined); const phone = process.env.EVOLUTION_DEFAULT_PHONE?.replace(/\D/g, ''); if (!phone) return { whatsappUrl: null, token }; const text = [typeof row.routing_code === 'string' ? row.routing_code : '', 'Hello — I have a question.', `#booka:${token}`].filter(Boolean).join(' '); return { whatsappUrl: `https://wa.me/${phone}?text=${encodeURIComponent(text)}`, token }; }, 'POST', { auth: false });
