import { LeadForm } from '@/components/capability/forms/LeadForm';
import { Card } from '@/components/capability/core/Card';
import { Container } from '@/components/capability/core/Container';
import { Heading } from '@/components/capability/core/Heading';
import { Section } from '@/components/capability/core/Section';
import { Text } from '@/components/capability/core/Text';
const fields = [{ name: 'name', label: 'Your name', required: true, placeholder: 'Name' }, { name: 'organisation', label: 'Organisation', placeholder: 'Organisation name' }, { name: 'email', label: 'Email address', type: 'email' as const, required: true, placeholder: 'you@example.com' }, { name: 'matter', label: 'General nature of your inquiry', type: 'textarea' as const, required: true, placeholder: 'Please do not include confidential information.' }];
export const metadata = { title: 'Request a consultation — Meridian Legal', description: 'A local-only consultation inquiry form in the Meridian Legal capability demonstrator.' };
export default function ContactPage() { return <main><Section><Container width="wide" className="grid gap-10 lg:grid-cols-[.85fr_1.15fr]"><div><p className="text-xs font-semibold uppercase tracking-[.18em]" style={{ color: 'var(--sc-primary)' }}>Contact</p><Heading level={1} className="mt-3">Request a consultation.</Heading><Text size="lg" tone="muted" className="mt-4">This is a local-only interaction pattern. No message is sent, stored, reviewed, or treated as a request for legal advice.</Text><Card className="mt-8 rounded-none"><Heading level={2} className="text-xl">Before you submit</Heading><Text tone="muted" className="mt-3">Do not include confidential information. A real firm would need to complete its own conflict check before deciding whether it can discuss a matter. Sending an inquiry does not create an attorney-client relationship.</Text></Card><p className="mt-6 text-sm" style={{ color: 'var(--sc-muted)' }}>Jurisdiction and professional obligations vary. This fictional demonstrator offers no legal advice.</p></div><Card className="rounded-none p-6 sm:p-8"><Heading level={2} className="text-2xl">Tell us the broad context</Heading><Text tone="muted" className="mt-2">The required fields and notice demonstrate a careful intake pattern only.</Text><div className="mt-7"><LeadForm fields={fields} submitLabel="Send consultation inquiry" privacyNote="This is a demonstrator form. No data is transmitted, stored, sent, or used for a conflict check." /></div></Card></Container></Section></main>; }
